       

class MyChineseWords  {
   static words = {
        "to be called": "叫",
        "surname, one’s family name is": "姓",
        "name": "名字",
        "a person of which country": "哪国人",
        "you": "你",
        "I, me": "我",
        "It's nice to meet you": "认识你很高兴",
        "is": "是",
        "United States": "美国",
        "China": "中国",
        "busy": "忙",
        "tired , tiring": "累",
        "good": "好",
        "you (plural), y'all": "你们",
        "student, students": "学生",
        "teacher": "老师",
        "goodbye": "再见",
        "Japan": "日本",
        "He, him": "他",
        "to want": "要",
        "to like": "喜欢",
        "to drink": "喝",
        "to eat": "吃",
        "coffee": "咖啡",
        "dish, cuisine": "菜",
        "tea": "茶",
        "measure word for family members": "口",
        "general measure word, measure word for people": "个",
        "father": "爸爸",
        "mother": "妈妈",
        "older brother": "哥哥",
        "older sister": "姐姐",
        "younger brother": "弟弟",
        "younger sister": "妹妹",
        "home, family": "家",
        "and": "和",
        "who": "谁",
        "dog": "狗",
        "good-looking": "好看",
        "book, books": "书",
        "siblings": "兄弟姐妹",
        "house": "房子",
        "family member": "家人",
        "to introduce": "介绍",
        "beautiful": "漂亮",
        "a measure word for photograph, picture, paper, table etc.": "张",
        "daughter": "女儿",
        "cat": "猫",
        "pictures, photos": "照片",
        "many, more": "多",
        "two": "两",
        "cute,lovely": "可爱",
        "piece； dollar": "块",
        "cup, cups": "杯",
        "bottle, bottles": "瓶",
        "buy": "买",
        "money": "钱",
        "thing, things, stuff": "东西",
        "Thank you": "谢谢",
        "You're welcome": "不客气",
        "some": "些",
        "hundred": "百",
        "altogether": "一共",
        "today": "今天",
        "What time": "几点",
        "minute": "分",
        "to read, to watch": "看",
        "movie": "电影",
        "Surf Internet": "上网",
        "now": "现在",
        "half": "半",
        "to do": "做",
        "to cook": "做饭",
        "to eat": "吃饭",
        "Excuse me, may I ask…": "请问",
        "restaurant": "饭馆",
        "waiter, waitress": "服务员",
        "cup": "杯子",
        "really": "真",
        "to order food": "点菜",
        "tasty/delicious": "好吃",
        "water": "水",
        "few": "少",
        "to pay": "买单",
        "yesterday": "昨天",
        "tomorrow": "明天",
        "when": "什么时候",
        "morning": "上午",
        "Week, day of the week": "星期",
        "wake up": "起床",
        "breakfast": "早饭",
        "sleep": "睡觉",
        "go to class,attend class": "上课",
        "to want to ,to plan to/to think": "想",
        "month": "月",
        "day": "日",
        "afternoon": "下午",
        "evening": "晚上",
        "to treat, to invite": "请",
        "to come": "来",
        "have free time, to be free": "有空",
        "sorry": "对不起",
        "that's ok, no problem": "没关系",
        "birthday": "生日",
        "to play ball games, ball sports": "打球",
        "basketball": "篮球",
        "match, ball games": "球赛",
        "shopping": "逛街",
        "weekend": "周末",
        "to wake up early": "早起",
        "to feel,to think,to consider": "觉得",
        "interesting, fun, enjoyable": "好玩儿",
        "exercise, to exercise": "运动",
        "cinema": "电影院",
        "to study": "学习",
        "bar": "酒吧",
        "beer": "啤酒",
        "interesting, fun": "有意思",
        "boring,bored": "无聊",
        "be annoyed,to bother, troublesome, annoying": "麻烦",
        "to go outside": "出门",
        "kind,type": "种",
        "together": "一起",
        "forget about it": "算了",
        "raining": "下雨",
        "outside": "外面",
        "no problem": "没问题",
        "but": "可是",
        "cooking": "做菜",
        "to sing": "唱歌",
        "say,speak a language": "说",
        "Mandarin": "汉语",
        "English": "英语",
        "pretty good, not bad": "不错",
        "to teach": "教",
        "to write": "写字",
        "fast, quick": "快",
        "homework": "功课",
        "library": "图书馆",
        "lunch": "中饭",
        "dinner": "晚饭",
        "noon": "中午",
        "very,extremely": "非常",
        "question": "题",
        "difficult": "难",
        "new": "新",
        "old, used, worn": "旧",
        "big": "大",
        "Measure word (for a cell phone etc)": "支",
        "shop, store": "商店",
        "cell phone": "手机",
        "look, have a look": "看一看",
        "ten thousand": "万",
        "thousand": "千",
        "to express ability": "能",
        "on top of": "上面",
        "down/under": "下面",
        "next to/beside": "旁边",
        "inside": "里面",
        "building": "大楼",
        "beach": "海边",
        "to live": "住",
        "to know": "知道",
        "to welcome, welcome": "欢迎",
        "to play, have fun": "玩儿",
        "bus": "公共汽车",
        "bicycle/bike": "自行车",
        "to walk": "走路",
        "stations, stops": "站",
        "chair": "椅子",
        "to take a rest": "休息",
        "to go to work": "上班",
        "to take (a bus, airplane etc)": "坐",
        "to ride": "骑",
        "supermarket": "超市",
        "Measure word (for events, things, clothes etc)": "件",
        "clothes": "衣服",
        "by the way": "对了",
        "to tell": "告诉",
        "egg": "鸡蛋",
        "to forget": "忘了",
        "milk": "牛奶",
        "how to...?": "怎么",
        "to get there,walk": "走",
        "front/forward/ahead": "前",
        "then,right away": "就",
        "post office": "邮局",
        "to know, to recognise": "认识",
        "road": "路",
        "to turn left": "左拐",
        "to turn right": "右拐",
        "from": "从",
        "to arrive, arrive": "到",
        "Affair,matter,thing": "事情",
        "must,have to": "得",
        "time": "时间",
        "to fear, to be afraid of": "怕",
        "anxious": "担心",
        "to test, test, exam": "考试",
        "this year": "今年",
        "excuse me": "不好意思",
        "to listen to music": "听音乐",
        "nearby": "附近",
        "to take a photo": "照相",
        "museum": "博物馆",
        "friend, friends": "朋友",
        "day": "天",
        "Wait a moment, later": "等一会儿",
        "area, place": "地方",
        "far": "远",
        "near": "近",
        "hour": "小时",
        "mountain": "山",
        "climb a mountain": "爬山",
        "company": "公司",
        "minute": "分钟",
        "require": "要",
        "convenient": "方便",
        "transportation ticket": "车票",
        "taxi": "出租车",
        "subway": "地铁",
        "to give somebody a ride": "载",
        "car": "汽车",
        "to drive or to open": "开",
        "scenery": "风景",
        "cheap": "便宜",
        "to wait": "等",
        "to be late": "迟到",
        "never": "从不",
        "to make an appointment/to invite.": "约",
        "last time": "上次",
        "already": "已经",
        "slow": "慢",
        "how long": "多久",
        "to practice": "练习",
        "to speak": "说话",
        "why": "为什么",
        "useful": "有用",
        "to have a vacation": "放假",
        "Because": "因为",
        "therefore": "所以",
        "just": "刚",
        "to see, to catch sight of": "看见",
        "before": "以前",
        "calligraphy": "书法",
        "to start": "开始",
        "school": "学校",
        "lesson, class": "课",
        "probably": "可能",
        "recently": "最近",
        "Hello (when answer the telephone)": "喂",
        "to hold a meeting": "开会",
        "to make a phone call": "打电话",
        "then, in that case": "那",
        "table": "桌子",
        "birthday party": "生日会",
        "apple pie": "苹果派",
        "to invite": "邀请",
        "long time, no see": "好久不见",
        "to give": "给",
        "gift": "礼物",
        "blue": "蓝色",
        "dumplings": "饺子",
        "travel": "旅游",
        "experience": "经验",
        "Measure word for enumerated events or how many times": "次",
        "happy": "快乐",
        "the most": "最",
        "famous": "有名",
        "airplane": "飞机",
        "to hear": "听说",
        "happy": "高兴",
        "hotel": "旅馆",
        "souvenir": "纪念品",
        "to plan, to plan to do sth.": "计划",
        "to get used to": "习惯",
        "last year": "去年",
        "to return to home country": "回国",
        "to plan": "打算",
        "Peking": "北京",
        "abroad/foreign country": "外国",
        "only": "只",
        "the day after tomorrow": "后天",
        "girlfreind": "女朋友",
        "to leave": "走",
        "to hate to part with": "舍不得",
        "classmate": "同学",
        "to miss": "想",
        "to write a letter": "写信",
        "to take (transportation)": "搭",
        "to come back": "回来",
        "weather": "天气",
        "cold": "冷",
        "hot": "热",
        "to ski": "滑雪",
        "to swim": "游泳",
        "to snow": "下雪",
        "comfortable": "舒服",
        "year old": "岁",
        "high；tall": "高",
        "so then...": "那么",
        "fat": "胖",
        "short": "矮",
        "thin": "瘦",
        "long": "长",
        "hair": "头发",
        "doctor": "医生",
        "to be sick": "生病",
        "to see a doctor": "看病",
        "medicine": "药",
        "body, health": "身体",
        "fruit": "水果",
        "vegetables": "蔬菜",
        "hospital": "医院",
        "to take a leave": "请假",
        "one, single": "一",
        "a little bit, a bit": "一点儿",
        "seven": "七",
        "three": "三",
        "on, on top of": "上",
        "under, off, leave": "下",
        "do not": "不",
        "nine": "九",
        "past tense": "了",
        "two": "二",
        "five": "五",
        "people, person": "人",
        "what": "什么",
        "to be able to, can do": "会",
        "son": "儿子",
        "eight": "八",
        "six": "六",
        "to write": "写",
        "a few": "几",
        "front, frontside": "前面",
        "ten": "十",
        "to go": "去",
        "number": "号",
        "behind, backside": "后面",
        "Do you?Is that?": "吗",
        "to listen, to hear": "听",
        "": "呢",
        "which": "哪",
        "where": "哪儿",
        "four": "四",
        "to go back, to return": "回",
        "in": "在",
        "How many": "多少",
        "too (as in too many)": "太",
        "she, her": "她",
        "word, character": "字",
        "small": "小",
        "Miss, Ms.": "小姐",
        "work, to work, job": "工作",
        "year": "年",
        "very, quite": "很",
        "how's this? how is it? how about that?": "怎么样",
        "we, us": "我们",
        "when (we were doing sth...), at the time": "时候",
        "to have, to own": "有",
        "measure word for books": "本",
        "to not have, don't have": "没有",
        "point, o'clock": "点",
        "television, TV": "电视",
        "of, possessive, belonging to": "的",
        "rice": "米饭",
        "apple": "苹果",
        "to read": "读",
        "this": "这",
        "all, every": "都",
        "in, inside": "里",
        "restaurant": "饭店",
        "special": "特别",
        "concert": "演唱会",
        "everyone": "大家",
        "to feel happy, to rejoice, to have a great time": "开心",
        "to dance": "跳舞",
        "famous": "有名",
        "singer": "歌手",
        "currency unit (esp. Chinese yuan)": "元",
        "as if, to seem like": "好像",
        "bottoms up , Cheers.": "干杯",
        "to stay": "待",
        "to relax": "放松",
        "to graduate": "毕业",
        "to associate (with), to date, (interpersonal) relationship": "交往",
        "once, previously, ever, (past tense marker used before Verb or clause)": "曾经",
        "at once, right away, immediately": "马上",
        "room": "房间",
        "cloudy": "阴天",
        "kitchen": "厨房",
        "cake": "蛋糕",
        "to be hungry": "饿",
        "milk": "牛奶",
        "to go out": "出去",
        "game": "游戏",
        "quiet, peaceful, calm": "安静",
        "park": "公园",
        "to discover": "发现",
        "to cross the street": "过马路",
        "concentrated": "专心",
        "danger, dangerous": "危险",
        "news": "新闻",
        "Attractions, scenic spot, place of interest (tourism)": "景点",
        "city": "城市",
        "building": "建筑",
        "season": "季节",
        "summer": "夏天",
        "to line up , queue up": "排队",
        "bustling with noise and excitement, lively": "热闹",
        "to bask in the sun": "晒太阳",
        "dessert；sweet": "甜食",
        "health, healthy": "健康",
        "Junk food": "垃圾食物",
        "to stay up late or all night": "熬夜",
        "last year": "去年",
        "love, to love": "爱",
        "to lose weight": "减肥",
        "fat": "胖",
        "important, significant, major": "重要",
        "to study abroad": "留学",
        "friendly": "友好",
        "Measure word for sealed objects, esp. letters": "封",
        "chopsticks": "筷子",
        "knife and fork": "刀叉",
        "Western": "西方",
        "a person's preferences, tastes (in food), flavor": "口味",
        "more or less,about the same": "差不多",
        "same, like, equal to, the same as, just like": "一样",
        "wind": "风",
        "forecast": "预报",
        "end of the month": "月底",
        "wet": "湿",
        "dry": "干",
        "to dislike, annoying": "讨厌",
        "temperature": "气温",
        "winter": "冬天",
        "to hold up an umbrella": "打伞",
        "to bring": "带",
        "to welcome, welcome": "欢迎",
        "to move (i.e. relocate oneself), to move (something relatively heavy or bulky)": "搬",
        "storied building, floor": "楼",
        "neighbor, next door": "邻居",
        "to help, to do a favor": "帮忙",
        "flower": "花",
        "to throw, to throw away": "扔",
        "wardrobe": "衣柜",
        "furniture store": "家具店",
        "bed": "床",
        "heavy": "重",
        "to need,to demand, to require, requirement": "需要",
        "to text, to send": "发",
        "text message": "短信",
        "quality": "质量",
        "to record, to note, to memorize": "记",
        "notebook": "笔记本",
        "to remember": "记得",
        "if, in case": "如果",
        "to propose, to suggest, suggestion, recommendation": "建议",
        "blackboard": "黑板",
        "method, way": "方法",
        "to hang or suspend (from a hook etc)": "挂",
        "to draw, painting": "画",
        "living room": "客厅",
        "window": "窗户",
        "sofa": "沙发",
        "orderly, neat, even, tidy": "整齐",
        "lamp, light, lantern": "灯",
        "chair": "椅子",
        "to put, to place": "放",
        "fish": "鱼",
        "shrimp, prawn": "虾",
        "to cook, to boil": "煮",
        "beef": "牛肉",
        "mutton, lamb meat": "羊肉",
        "way of handling something, method for making, work method, recipe,": "做法",
        "measure word for tables of guests at a banquet etc": "桌",
        "reason": "原因",
        "to pick up food with chopsticks": "夹",
        "to wrap (something in a bag), to load, to pack": "装",
        "to open, to turn on, to switch on": "打开",
        "to hold, to seize, to catch, to take": "拿",
        "luggage": "行李",
        "pocket": "口袋",
        "water bottle": "水瓶",
        "coins": "钱币",
        "passport": "护照",
        "key": "钥匙",
        "visa": "签证",
        "airport": "机场",
        "to see, to catch sight of": "看到",
        "(long) time, (long) duration of time": "久",
        "probably, roughly, approximately, about,": "大概",
        "so much, this much": "这么",
        "surely, certainly": "一定",
        "to pick up (the phone), to answer (the phone)": "接",
        "empty": "空",
        "landlord": "房东",
        "tenant": "房客",
        "transportation/traffic": "交通",
        "assistance, aid, to help, to assist": "帮助",
        "suitable, fitting": "合适",
        "to change, to switch": "换",
        "section of a room or lateral space between two pairs of pillars, Measure word for rooms": "间",
        "to make a noise, noisy": "吵",
        "other, (something or somebody) else, the rest": "其他",
        "usually": "平常",
        "bathroom": "洗手间",
        "culture": "文化",
        "to be convinced (that something is true), to believe,": "相信",
        "opportunity, chance,": "机会",
        "to review": "复习",
        "next time": "下次",
        "to understand, to comprehend": "懂",
        "oneself/myself/ownself": "自己",
        "Beijing Opera, Peking Opera": "京剧",
        "performance,perform": "表演",
        "brilliant, marverlous": "精彩",
        "What's up?, What's going on?, What happened?": "怎么了？",
        "to quarrel": "吵架",
        "complexion, look": "脸色",
        "boyfriend": "男朋友",
        "to cry, to weep": "哭",
        "to talk about": "谈一谈",
        "ugly, unsightly": "难看",
        "happen, occur, take place": "发生",
        "misunderstanding, misunderstand": "误会",
        "computer": "电脑",
        "Measure word for vehicles or machines": "台",
        "to give a discount": "打折",
        "to accompany, to keep somebody company": "陪",
        "bank": "银行",
        "parents": "父母",
        "department store": "百货公司",
        "refrigerator": "冰箱",
        "second-hand (information, equipment etc)": "二手",
        "original, former": "原来",
        "relaxed,to relaxed": "轻松",
        "to set off, to start (on a journey)": "出发",
        "history": "历史",
        "modern times, modern age, modern era": "现代",
        "city center, downtown": "市中心",
        "to prohibit, to forbid, to ban": "禁止",
        "to stroll, to visit": "逛",
        "style": "风格",
        "certainly, of course": "当然",
        "to lose the way, lost,": "迷路",
        "to get on or into (a bus, train, car etc)": "上车",
        "sunny day": "晴天",
        "there's not enough time (to do something), it's too late (to do something)": "来不及",
        "then, after that": "然后",
        "at once, immediately": "赶快",
        "to get off or out of (a bus, train, car etc)": "下车",
        "hurried, to make (somebody) anxious": "急",
        "to do, to manage, to handle, to play with, to fool with, to mess with, to fix, to toy with": "弄",
        "bad, spoiled, broken, to break down": "坏",
        "to get angry, angry": "生气",
        "heedless, careless": "不小心",
        "to move (house)": "搬家",
        "to treat, to invite to dinner": "请客",
        "to arrange, to tidy up": "整理",
        "to sweep the floor,": "扫地",
        "to break, to smash": "打破",
        "to lose": "丢",
        "to have an accident, to meet with a mishap": "出事",
        "strange, odd": "奇怪",
        "muddled, silly, confused": "糊涂",
        "to have disappeared, to be missing": "不见",
        "to feel sad, to feel unwell": "难过",
        "luckily, fortunately": "好在",
        "Dont rush, dont be anxious": "别急",
        "thief": "小偷",
        "to steal": "偷",
        "to put on or wear (glasses, hat, gloves etc)": "戴",
        "to carry on the back or shoulder": "背",
        "hat, cap": "帽子",
        "spectacles, eyeglasses": "眼镜",
        "knapsack,backpack": "背包",
        "shoes": "鞋",
        "shirt, blouse": "衬衫",
        "trousers, pants": "裤子",
        "a pair of": "双",
        "to run": "跑",
        "police, police officer": "警察",
        "no wonder!, so that's why!": "怪不得",
        "approximately": "左右",
        "competition (sports etc), match": "比赛",
        "to beat, to win": "赢",
        "to score a goal": "进球",
        "bald": "秃",
        "charming": "魅力",
        "sports star (ball sport)": "球星",
        "to pass": "经过",
        "round shape": "圆",
        "husband": "丈夫",
        "measure word for people (honorific)": "位",
        "eye": "眼睛",
        "wife": "妻子",
        "face": "脸",
        "height, stature": "个子",
        "Mr., husband": "先生",
        "almost, nearly": "差不多",
        "tremendous, awesome": "厉害",
        "listening skill/ hearing": "听力",
        "great effort, to try hard": "努力",
        "to improve, to get ahead": "进步",
        "nervous": "紧张",
        "difficult": "难",
        "easy": "容易",
        "to pass": "过",
        "to understand, to realize": "明白",
        "to believe, to think": "认为",
        "auspicious, lucky, propitious": "吉利",
        "to get rich": "发财",
        "number": "数字",
        "meaning": "意思",
        "friendship": "友谊",
        "to live, alive": "活",
        "to have a date": "约会",
        "to place an order, to book ahead": "预订",
        "restaurant": "餐厅",
        "on time, punctual, on schedule": "准时",
        "to laugh, to smile": "笑",
        "doorway, gate": "门口",
        "Measure word for families or businesses,": "家",
        "Valentine's Day": "情人节",
        "(used after a verb) in a while, give it a try": "一下儿",
        "to celebrate": "庆祝",
        "colleague, co-worker": "同事",
        "to find": "找到",
        "congratulations": "恭喜",
        "to finish work, to get off work": "下班",
        "environment, circumstances, surroundings": "环境",
        "tour guide": "导游",
        "culinary delicacy, fine food": "美食",
        "to read a book, to study, to attend school": "读书",
        "magazine": "杂志",
        "to recline, to lie down": "躺",
        "to fall asleep": "睡着",
        "to cough": "咳嗽",
        "in the end": "结果",
        "whole": "整个",
        "how terrible, what bad luck, terrible, bad": "糟糕",
        "to be touched (somebody emotionally)": "感动",
        "regret, to regret, to be sorry that": "遗憾",
        "to meet, to see each other": "见面",
        "party, gathering": "聚会",
        "to get in touch with, to contact, to link": "联系",
        "to be sorry, to feel apologetic": "抱歉",
        "to prepare": "准备",
        "surprise": "惊喜",
        "purse, wallet": "钱包",
        "color": "颜色",
        "service desk, information desk, reception desk": "服务台",
        "ID": "证件",
        "cash": "现金",
        "to take away": "拿走",
        "credit card": "信用卡",
        "to receive": "收到",
        "address": "地址",
        "to send": "寄",
        "package": "包裹",
        "sweater": "毛衣",
        "to test, to try": "试",
        "case/box": "盒子",
        "to take note of, to pay attention to": "注意",
        "to take care of, to show consideration, to attend to, to look after": "照顾",
        "vigor, vitality, drive, spiritual": "精神",
        "physical strength, physical power": "体力",
        "influence, effect, to influence, to affect (usually adversely), to disturb": "影响",
        "school assignment, homework,": "作业",
        "kung fu": "功夫",
        "to wake up, to get up": "起来",
        "to wish for, to desire, hope": "希望",
        "to avail oneself of, to take advantage of": "趁",
        "day, a (calendar) date, days of one's life": "日子",
        "to continue, to proceed with, to go on with": "继续",
        "like this, this way": "这样",
        "to leave, to bid farewell to, to say good-bye to": "告别",
        "(there are) some (who are...), some (exist)": "有的",
        "to see off": "送",
        "towards": "向",
        "farewell party, going away party": "欢送会",
        "to marry, to get married": "结婚",
        "totally, entirely": "完全",
        "to fall, to collapse,": "倒",
        "legend, folklore, tradition": "传说",
        "to build, to construct": "建",
        "to grab, to catch, to arrest": "抓",
        "whole nation, nationwide": "全国",
        "the Great Wall": "长城",
        "story, tale": "故事",
        "a bit": "一下",
        "and also": "也",
        "again, once more": "再",
        "out, outer, outside": "出",
        "do not, don't do sth.": "别",
        "to sell": "卖",
        "to be able to, can": "可以",
        "right, right side": "右边",
        "Right now": "吧",
        "Because Therefore…": "因为…所以…",
        "outer, outside": "外",
        "female, feminine": "女",
        "it": "它",
        "to finish": "完",
        "hotel, guest house, lodge": "宾馆",
        "Correct": "对",
        "left, left side": "左边",
        "to": "往",
        "you (polite form)": "您",
        "watch, a wristwatch": "手表",
        "to play basketball": "打篮球",
        "to find": "找",
        "classroom": "教室",
        "morning": "早上",
        "clear, sunny": "晴",
        "Is on": "正在",
        "each, every": "每",
        "ratio": "比",
        "to wash, to clean": "洗",
        "train station": "火车站",
        "to play, to have fun, to hang out": "玩",
        "man, male, masculine": "男",
        "an action currently happening , -ing": "着",
        "ticket": "票",
        "from": "离",
        "to wear, to dress": "穿",
        "the first, 1st, number one": "第一",
        "red": "红",
        "However, although…": "虽然…但是…",
        "watermelon": "西瓜",
        "to let, make, allow, cause": "让",
        "expensive": "贵",
        "to run": "跑步",
        "to play soccer": "踢足球",
        "also, or": "还",
        "to enter": "进",
        "pencil": "铅笔",
        "wrong, to wrong, to err, error, mistake": "错",
        "door": "门",
        "to ask, to inquire": "问",
        "cloudy": "阴",
        "snow": "雪",
        "zero": "零",
        "noodles": "面条",
        "black": "黑",
        "to dream": "做梦",
        "to call": "叫",
        "That's right!": "没错",
        "to despise, to underestimate": "小看",
        "deal": "说定了",
        "soup": "汤",
        "show": "露一手",
        "to raise, to bring up, to cultivate": "养",
        "finally": "终于",
        "to feel relived, to feel reassured, to be at ease": "放心",
        "to register, to sign up": "报名",
        "to dare": "敢",
        "to be afraid": "害怕",
        "street": "街道",
        "measure word for car": "辆",
        "driver's license": "驾照",
        "original, at first": "原来",
        "ticket (for theater, cinema etc)": "门票",
        "cost": "费用",
        "insurance": "保险",
        "traveler, tourist": "游客",
        "to be overdue, to exceed the time limit, to expire": "过期",
        "travel agency": "旅行社",
        "places of historic interest, historical sites": "古迹",
        "Asia": "亚洲",
        "tour group": "旅行团",
        "place, site, location, venue": "地点",
        "Europe": "欧洲",
        "Italy": "意大利",
        "Germany": "德国",
        "characteristic, distinguishing feature or quality": "特色",
        "to arrange, to plan, to set up, arrangements, plans": "安排",
        "itinerary": "行程",
        "climate": "气候",
        "for example": "比如说",
        "one of something": "之一",
        "ancient, old": "古老",
        "to participate, to attend": "参加",
        "Spain": "西班牙",
        "contract": "合同",
        "specialized field, main field of study (at university), major": "专业",
        "to notify, to inform, notice, notification": "通知",
        "to agree, to consent, to approve": "同意",
        "to be, to act as": "当",
        "news, information": "消息",
        "to be worried; to be distressed; worries": "烦恼",
        "development; growth; to develop; to grow; to expand": "发展",
        "to catch cold; (common) cold": "感冒",
        "to give or have an injection": "打针",
        "serious": "严重",
        "to have a high temperature (from illness); to have a fever": "发烧",
        "to feel unwell; to suffer pain; to be difficult to bear": "难受",
        "inspection; to examine; to inspect": "检查",
        "throat; voice": "嗓子",
        "to stay up late": "晚睡",
        "to worry; to feel anxious": "着急",
        "to work a temporary or casual job; (of students) to have a job outside of class time, or during vacation": "打工",
        "to earn money": "赚钱",
        "educational background; academic qualifications": "学历",
        "to hire": "请",
        "simple; not complicated": "简单",
        "to decide (to do something); to resolve; decision; certainly": "决定",
        "to suffer": "吃苦头",
        "do business": "做生意",
        "meaningful": "有意义",
        "male addicted to computers, computer games, adult cartoons etc": "宅男",
        "all day long; whole day": "整天",
        "interest; hobby": "爱好",
        "frequently; constantly; regularly; often; day-to-day; everyday; daily": "经常",
        "to go; take out (relates to food bought at a restaurant)": "外卖",
        "to enjoy; to live it up; pleasure": "享受",
        "lively": "活泼",
        "outdoor": "户外",
        "activity": "活动",
        "holiday, non-working day": "假日",
        "roommate": "同屋",
        "to make friends": "交",
        "to meet": "遇到",
        "by chance, by coincidence, to happen to": "好巧",
        "exchange students": "交换学生",
        "dorm room": "宿舍",
        "to be familiar with, to know well": "熟悉",
        "cordial, enthusiastic, passion, passionate, passionately": "热情",
        "attire, clothes, dress": "穿着",
        "to dress, to make up": "打扮",
        "to change, to become different, to transform": "变",
        "fashionable": "时髦",
        "to feel, to sense, to have the feeling that": "感到",
        "price": "价钱",
        "vacation": "假期",
        "beach, sandy shore": "沙滩",
        "swimming pool": "游泳池",
        "unforgettable": "难忘",
        "south": "南",
        "north": "北",
        "east": "东",
        "west": "西",
        "benefit, advantage": "好处",
        "interest, hobby": "兴趣",
        "to engage in physical exercise, to work out": "锻炼",
        "gym": "健身房",
        "to climb a mountain": "登山",
        "to choose, to pick, to select, to elect, choice": "选择",
        "harm, disadvantage": "坏处",
        "to persevere with, to persist in": "坚持",
        "to complete, to accomplish": "完成",
        "must, need to, have to": "必须",
        "but, however, only, merely": "不过",
        "just now": "刚才",
        "midnight": "半夜",
        "to apply for job": "应征",
        "commercial, advertise": "广告",
        "everywhere": "到处",
        "easy": "容易",
        "clear, to understand": "清楚",
        "the first step, step one": "第一步",
        "the next step, then": "下一步",
        "fry (meat, fish, or vegetables) rapidly over a high heat while stirring briskly": "炒",
        "tomato": "西红柿",
        "recipe": "食谱",
        "upside down, pour, collapse, fail": "倒",
        "oil, fat": "油",
        "courses in a meal": "道",
        "greasy, oily": "油腻",
        "salt": "盐",
        "light, weak, delicate, mild": "清淡",
        "to cut": "切",
        "to get": "得",
        "symtom": "症状",
        "nothing serious, doesn't matter,Never mind": "没事",
        "(body)temperature": "体温",
        "to measure": "量",
        "useless": "没用",
        "serious, important , critical": "要紧",
        "necessary": "必要",
        "to delay": "耽误",
        "to stop, to halt, to freeze": "站住",
        "solution, method, way": "办法",
        "to understand, to find out": "了解",
        "autumn, fall": "秋天",
        "young": "年轻",
        "problem, question, issue, matter": "问题",
        "to solve, to settle": "解决",
        "businessman": "生意人",
        "dirty, dishonest": "黑心",
        "all family": "全家",
        "to report（an incident）to the police": "报警",
        "failure, to fail": "失败",
        "rare, hard": "难得",
        "maybe": "也许",
        "to park": "停",
        "always": "总是",
        "full (to eat till full)": "饱",
        "to find time to do something": "抽空",
        "king": "国王",
        "previous": "从前",
        "animal": "动物",
        "elephant": "大象",
        "curious": "好奇",
        "mark": "记号",
        "to draw, painting": "画",
        "boat": "船",
        "idea": "主意",
        "to sink": "下沉",
        "popular, fashionable": "流行",
        "to dress up, to make up , dress, way or style of dressing": "打扮",
        "green": "绿",
        "to match": "配",
        "purple": "紫",
        "to worry about": "操心",
        "charm": "魅力",
        "to care about": "在乎",
        "dream, ideal": "理想",
        "driver": "司机",
        "diplomat": "外交官",
        "pay, wages": "工资",
        "to stay, leave behind": "留",
        "nurse": "护士",
        "for": "为",
        "service": "服务",
        "desire, wish": "愿望",
        "to fulfil, to come true": "实现",
        "to hide the truth from": "瞒",
        "only daughter": "独生女",
        "free, freedom": "自由",
        "to consult, to discuss": "商量",
        "truth": "实话",
        "to leave, to depart": "离别",
        "online": "网上",
        "to shop (shopping)": "购物",
        "to withdraw (a product)": "退",
        "reliable, trustworthy": "可靠",
        "brand": "牌子",
        "to try wearing clothes, fitting trial": "试穿",
        "products": "用品",
        "inferior": "差",
        "bank account": "户头",
        "to do, to handle, to manage": "办",
        "procedures": "手续",
        "to transfer account": "转账",
        "automatically": "自动",
        "receipt": "收据",
        "to pay a fee": "缴费",
        "to verbally abuse , call names": "骂",
        "to think over, to consider": "考虑",
        "to recommend": "推荐",
        "it is a pity, what a pity, unfortunately": "可惜",
        "worthwhile, value for money, to view as profitable": "划算",
        "to guarantee, to assure": "保证",
        "headphones, earphones, telephone receiver": "耳机",
        "to repair, to build": "修",
        "waterproof": "防水",
        "to request, to require, the other party's wishes and conditions": "要求",
        "suggestion": "意见",
        "situation": "情况",
        "elder family members": "长辈",
        "younger family members": "晚辈",
        "each": "各",
        "last generation": "上一代",
        "background": "背景",
        "to sum up, overall": "总之",
        "opinion": "想法",
        "fortunately, luckily": "幸亏",
        "grave, serious, severe, critical": "严重",
        "to sustain injuries, be wounded, be harmed (in an accident etc)​": "受伤",
        "to bump into, to hit": "撞到",
        "tree": "树",
        "accident": "事故",
        "ambulance": "救护车",
        "classifier for trees, cabbages, plants etc": "棵",
        "voice, sound": "声音",
        "to dye": "染",
        "eye-catching": "醒目",
        "private life": "私生活",
        "to intervene": "干涉",
        "to concede, concession": "让步",
        "to get sick because of bad food": "吃坏肚子",
        "fresh": "新鲜",
        "to have diarrhea": "拉肚子",
        "painful": "疼",
        "emergency": "急诊",
        "to inject": "打针",
        "cooked, done": "熟",
        "lamb meat": "羊肉",
        "sea food": "海鲜",
        "watch": "表",
        "a unit that calculates blocks or pieces": "块",
        "style, type": "样式",
        "here": "这边",
        "famous and valuable, rare, precious": "名贵",
        "to pack, to package": "包装",
        "to produce": "产",
        "to be willing to": "愿意",
        }

        static getWords(){
                return MyChineseWords.words;
        }
}

export default MyChineseWords;