       

class MyChineseWords  {
   static words = {
        "to be called": "叫:jiào",
        "surname, one’s family name is": "姓:xìng",
        "name": "名字:míngzi",
        "a person of which country": "哪国人:nǎguórén",
        "you": "你:nǐ",
        "I, me": "我:wǒ",
        "It's nice to meet you": "认识你很高兴:rènshì nǐ hěn gāoxìng",
        "is": "是:shì",
        "United States": "美国:Měiguó",
        "China": "中国:Zhōngguó",
        "busy": "忙:máng",
        "tired , tiring": "累:lèi",
        "good": "好:hǎo",
        "you (plural), y'all": "你们:nǐmen",
        "student, students": "学生:xuéshēng",
        "teacher": "老师:lǎoshī",
        "goodbye": "再见:zàijiàn",
        "Japan": "日本:Rìběn",
        "He, him": "他:tā",
        "to want": "要:yào",
        "to like": "喜欢:xǐhuan",
        "to drink": "喝:hē",
        "to eat": "吃:chī",
        "coffee": "咖啡:kāfēi",
        "dish, cuisine": "菜:cài",
        "tea": "茶:chá",
        "measure word for family members": "口:kǒu",
        "general measure word, measure word for people": "个:gè",
        "father": "爸爸:bàba",
        "mother": "妈妈:māma",
        "older brother": "哥哥:gēge",
        "older sister": "姐姐:jiějie",
        "younger brother": "弟弟:dìdi",
        "younger sister": "妹妹:mèimei",
        "home, family": "家:jiā",
        "and": "和:hé",
        "who": "谁:shéi",
        "dog": "狗:gǒu",
        "good-looking": "好看:hǎokàn",
        "book, books": "书:shū",
        "siblings": "兄弟姐妹:xiōngdì jiěmèi",
        "house": "房子:fángzi",
        "family member": "家人:jiārén",
        "to introduce": "介绍:jièshào",
        "beautiful": "漂亮:piàoliàng",
        "a measure word for photograph, picture, paper, table etc.": "张:zhāng",
        "daughter": "女儿:nǚér",
        "cat": "猫:māo",
        "pictures, photos": "照片:zhàopiàn",
        "many, more": "多:duō",
        "two": "两:liǎng",
        "cute,lovely": "可爱:kěài",
        "piece； dollar": "块:kuài",
        "cup, cups": "杯:bēi",
        "bottle, bottles": "瓶:píng",
        "buy": "买:mǎi",
        "money": "钱:qián",
        "thing, things, stuff": "东西:dōngxi",
        "Thank you": "谢谢:xièxie",
        "You're welcome": "不客气:búkèqì",
        "some": "些:xiē",
        "hundred": "百:bǎi",
        "altogether": "一共:yígòng",
        "today": "今天:jīntiān",
        "What time": "几点:jǐdiǎn",
        "minute": "分:fēn",
        "to read, to watch": "看:kàn",
        "movie": "电影:diànyǐng",
        "Surf Internet": "上网:shàngwǎng",
        "now": "现在:xiànzài",
        "half": "半:bàn",
        "to do": "做:zuò",
        "to cook": "做饭:zuòfàn",
        "to eat": "吃饭:chīfàn",
        "Excuse me, may I ask…": "请问:qǐngwèn",
        "restaurant": "饭馆:fànguǎn",
        "waiter, waitress": "服务员:fúwùyuán",
        "cup": "杯子:bēizi",
        "really": "真:zhēn",
        "to order food": "点菜:diǎncài",
        "tasty/delicious": "好吃:hǎochī",
        "water": "水:shuǐ",
        "few": "少:shǎo",
        "to pay": "买单:mǎidān",
        "yesterday": "昨天:zuótiān",
        "tomorrow": "明天:míngtiān",
        "when": "什么时候:shénme shíhou",
        "morning": "上午:shàngwǔ",
        "Week, day of the week": "星期:xīngqī",
        "wake up": "起床:qǐchuáng",
        "breakfast": "早饭:zǎofàn",
        "sleep": "睡觉:shuìjiào",
        "go to class,attend class": "上课:shàngkè",
        "to want to ,to plan to/to think": "想:xiǎng",
        "month": "月:yuè",
        "day": "日:rì",
        "afternoon": "下午:xiàwǔ",
        "evening": "晚上:wǎnshàng",
        "to treat, to invite": "请:qǐng",
        "to come": "来:lái",
        "have free time, to be free": "有空:yǒukòng",
        "sorry": "对不起:duìbùqǐ",
        "that's ok, no problem": "没关系:méiguānxi",
        "birthday": "生日:shēngrì",
        "to play ball games, ball sports": "打球:dǎqiú",
        "basketball": "篮球:lánqiú",
        "match, ball games": "球赛:qiúsài",
        "shopping": "逛街:guàngjiē",
        "weekend": "周末:zhōumò",
        "to wake up early": "早起:zǎoqǐ",
        "to feel,to think,to consider": "觉得:juéde",
        "interesting, fun, enjoyable": "好玩儿:hǎowán'er",
        "exercise, to exercise": "运动:yùndòng",
        "cinema": "电影院:diànyǐngyuàn",
        "to study": "学习:xuéxí",
        "bar": "酒吧:jiǔba",
        "beer": "啤酒:píjiǔ",
        "interesting, fun": "有意思:yǒuyìsi",
        "boring,bored": "无聊:wúliáo",
        "be annoyed,to bother, troublesome, annoying": "麻烦:máfán",
        "to go outside": "出门:chūmén",
        "kind,type": "种:zhǒng",
        "together": "一起:yìqǐ",
        "forget about it": "算了:suànle",
        "raining": "下雨:xiàyǔ",
        "outside": "外面:wàimiàn",
        "no problem": "没问题:méi wèntí",
        "but": "可是:kěshì",
        "cooking": "做菜:zuòcài",
        "to sing": "唱歌:chànggē",
        "say,speak a language": "说:shuō",
        "Mandarin": "汉语:hànyǔ",
        "English": "英语:yīngyǔ",
        "pretty good, not bad": "不错:búcuò",
        "to teach": "教:jiāo",
        "to write": "写字:xiězì",
        "fast, quick": "快:kuài",
        "homework": "功课:gōngkè",
        "library": "图书馆:túshūguǎn",
        "lunch": "中饭:zhōngfàn",
        "dinner": "晚饭:wǎnfàn",
        "noon": "中午:zhōngwǔ",
        "very,extremely": "非常:fēicháng",
        "question": "题:tí",
        "difficult": "难:nán",
        "new": "新:xīn",
        "old, used, worn": "旧:jiù",
        "big": "大:dà",
        "Measure word (for a cell phone etc)": "支:zhī",
        "shop, store": "商店:shāngdiàn",
        "cell phone": "手机:shǒujī",
        "look, have a look": "看一看:kànyíkàn",
        "ten thousand": "万:wàn",
        "thousand": "千:qiān",
        "to express ability": "能:néng",
        "on top of": "上面:shàngmiàn",
        "down/under": "下面:xiàmiàn",
        "next to/beside": "旁边:pángbiān",
        "inside": "里面:lǐmiàn",
        "building": "大楼:dàlóu",
        "beach": "海边:hǎibiān",
        "to live": "住:zhù",
        "to know": "知道:zhīdào",
        "to welcome, welcome": "欢迎:huānyíng",
        "to play, have fun": "玩儿:wánr",
        "bus": "公共汽车:gōnggòng qìchē",
        "bicycle/bike": "自行车:zìxíngchē",
        "to walk": "走路:zǒulù",
        "stations, stops": "站:zhàn",
        "chair": "椅子:yǐzi",
        "to take a rest": "休息:xiūxí",
        "to go to work": "上班:shàngbān",
        "to take (a bus, airplane etc)": "坐:zuò",
        "to ride": "骑:qí",
        "supermarket": "超市:chāoshì",
        "Measure word (for events, things, clothes etc)": "件:jiàn",
        "clothes": "衣服:yīfú",
        "by the way": "对了:duìle",
        "to tell": "告诉:gàosù",
        "egg": "鸡蛋:jīdàn",
        "to forget": "忘了:wàngle",
        "milk": "牛奶:niúnǎi",
        "how to...?": "怎么:zěnme",
        "to get there,walk": "走:zǒu",
        "front/forward/ahead": "前:qián",
        "then,right away": "就:jiù",
        "post office": "邮局:yóujú",
        "to know, to recognise": "认识:rènshì",
        "road": "路:lù",
        "to turn left": "左拐:zuǒguǎi",
        "to turn right": "右拐:yòuguǎi",
        "from": "从:cóng",
        "to arrive, arrive": "到:dào",
        "Affair,matter,thing": "事情:shìqíng",
        "must,have to": "得:děi",
        "time": "时间:shíjiān",
        "to fear, to be afraid of": "怕:pà",
        "anxious,worried,to worry": "担心:dānxīn",
        "to test, test, exam": "考试:kǎoshì",
        "this year": "今年:jīnnián",
        "excuse me, to be sorry": "不好意思:bùhǎoyìsi",
        "to listen to music": "听音乐:tīng yīnyuè",
        "nearby": "附近:fùjìn",
        "to take a photo": "照相:zhàoxiàng",
        "museum": "博物馆:bówùguǎn",
        "friend, friends": "朋友:péngyǒu",
        "day": "天:tiān",
        "Wait a moment, later": "等一会儿:děng yìhuǐr",
        "area, place": "地方:dìfāng",
        "far": "远:yuǎn",
        "near/close": "近:jìn",
        "hour": "小时:xiǎoshí",
        "mountain": "山:shān",
        "to climb a mountain, to hike a mountain": "爬山:páshān",
        "company": "公司:gōngsī",
        "minute": "分钟:fēnzhōng",
        "to need, require": "要:yào",
        "convenient": "方便:fāngbiàn",
        "transportation ticket": "车票:chēpiào",
        "taxi": "出租车:chūzūchē",
        "subway, metro": "地铁:dìtiě",
        "to give somebody a ride": "载:zài",
        "car": "汽车:qìchē",
        "to drive ( a machine, car, airplan), to open": "开:kāi",
        "scenery": "风景:fēngjǐng",
        "cheap": "便宜:piányí",
        "to wait": "等:děng",
        "to be late": "迟到:chídào",
        "never": "从不:cóng bù",
        "to make an appointment/to invite.": "约:yuē",
        "last time": "上次:shàngcì",
        "already": "已经:yǐjīng",
        "slow": "慢:màn",
        "how long..?": "多久:duōjiǔ",
        "to practice": "练习:liànxí",
        "to speak/ to talk": "说话:shuōhuà",
        "why": "为什么:wèishénme",
        "useful": "有用:yǒuyòng",
        "to have a vacation": "放假:fàngjià",
        "Because": "因为:yīnwèi",
        "therefore": "所以:suǒyǐ",
        "just": "刚:gāng",
        "to see, to catch sight of": "看见:kànjiàn",
        "Noun/ before": "以前:yǐqián",
        "calligraphy": "书法:shūfǎ",
        "to start": "开始:kāishǐ",
        "school": "学校:xuéxiào",
        "lesson, class": "课:kè",
        "maybe, might, probably": "可能:kěnéng",
        "recently": "最近:zuìjìn",
        "Hello (when answer the telephone)": "喂:wéi",
        "to hold a meeting": "开会:kāihuì",
        "to make a phone call": "打电话:dǎdiànhuà",
        "then, in that case": "那:nà",
        "table": "桌子:zhuōzi",
        "birthday party": "生日会:shēngrì huì",
        "apple pie": "苹果派:píngguǒ pài",
        "to invite": "邀请:yāoqǐng",
        "long time, no see": "好久不见:hǎojiǔ bújiàn",
        "to give": "给:gěi",
        "gift": "礼物:lǐwù",
        "blue": "蓝色:lánsè",
        "dumplings": "饺子:jiǎozi",
        "travel": "旅游:lǚyóu",
        "experience": "经验:jīngyàn",
        "Measure word for enumerated events, time": "次:cì",
        "happy": "快乐:kuàile",
        "the most": "最:zuì",
        "famous": "有名:yǒumíng",
        "airplane": "飞机:fēijī",
        "to hear (sb. said)": "听说:tīngshuō",
        "glad, happy": "高兴:gāoxìng",
        "hostel, hotel": "旅馆:lǚguǎn",
        "souvenir": "纪念品:jìniànpǐn",
        "to plan, to plan to do sth.": "计划:jìhuà",
        "to get used to": "习惯:xíguàn",
        "last year": "去年:qùnián",
        "to return to home country": "回国:huíguó",
        "to plan": "打算:dǎsuàn",
        "Peking": "北京:běijīng",
        "abroad/foreign country": "外国:wàiguó",
        "only": "只:zhǐ",
        "the day after tomorrow": "后天:hòutiān",
        "girlfreind": "女朋友:nǚpéngyou",
        "to leave": "走:zǒu",
        "to hate to part with": "舍不得:shěbude",
        "classmate": "同学:tóngxué",
        "to miss": "想:xiǎng",
        "to write a letter": "写信:xiě xìn",
        "to take (transportation)": "搭:dā",
        "to come back": "回来:huílái",
        "weather": "天气:tiānqì",
        "cold": "冷:lěng",
        "hot": "热:rè",
        "to ski": "滑雪:huáxuě",
        "to swim": "游泳:yóuyǒng",
        "to snow": "下雪:xiàxuě",
        "comfortable": "舒服:shūfu",
        "year old": "岁:suì",
        "high；tall": "高:gāo",
        "so then...": "那么:nàme",
        "fat": "胖:pàng",
        "short": "矮:ǎi",
        "thin": "瘦:shòu",
        "long": "长:cháng",
        "hair": "头发:tóufà",
        "doctor": "医生:yīshēng",
        "to be sick": "生病:shēngbìng",
        "to see a doctor": "看病:kànbìng",
        "medicine": "药:yào",
        "body, health": "身体:shēntǐ",
        "fruit": "水果:shuǐguǒ",
        "vegetables": "蔬菜:shūcài",
        "hospital": "医院:yīyuàn",
        "to take a leave": "请假:qǐngjià",
        "one, single": "一:yī",
        "a little bit, a bit": "一点儿:yìdiǎnr",
        "seven": "七:qī",
        "three": "三:sān",
        "on, on top of": "上:shàng",
        "under, off, leave": "下:xià",
        "do not": "不:bù",
        "nine": "九:jiǔ",
        "past tense": "了:le",
        "two": "二:èr",
        "five": "五:wǔ",
        "people, person": "人:rén",
        "what": "什么:shénme",
        "to be able to, can do": "会:huì",
        "son": "儿子:érzi",
        "eight": "八:bā",
        "six": "六:liù",
        "to write": "写:xiě",
        "a few": "几:jǐ",
        "front, frontside": "前面:qiánmiàn",
        "ten": "十:shí",
        "to go": "去:qù",
        "number": "号:hào",
        "behind, backside": "后面:hòumiàn",
        "Do you?Is that?": "吗:ma",
        "to listen, to hear": "听:tīng",
        "": "呢:ne",
        "which": "哪:nǎ",
        "where": "哪儿:nǎ'er",
        "four": "四:sì",
        "to go back, to return": "回:huí",
        "in": "在:zài",
        "How many": "多少:duōshǎo",
        "too (as in too many)": "太:tài",
        "she, her": "她:tā",
        "word, character": "字:zì",
        "small": "小:xiǎo",
        "Miss, Ms.": "小姐:xiǎojiě",
        "work, to work, job": "工作:gōngzuò",
        "year": "年:nián",
        "very, quite": "很:hěn",
        "how's this? how is it? how about that?": "怎么样:zěnmeyàng",
        "we, us": "我们:wǒmen",
        "when (we were doing sth...), at the time": "时候:shíhòu",
        "to have, to own": "有:yǒu",
        "measure word for books": "本:běn",
        "to not have, don't have": "没有:méiyǒu",
        "point, o'clock": "点:diǎn",
        "television, TV": "电视:diànshì",
        "of, possessive, belonging to": "的:de",
        "rice": "米饭:mǐfàn",
        "apple": "苹果:píngguǒ",
        "to read": "读:dú",
        "this": "这:zhè",
        "all, every": "都:dōu",
        "in, inside": "里:lǐ",
        "restaurant": "饭店:fàndiàn",
        "special": "特别:tèbié",
        "concert": "演唱会:yǎnchànghuì",
        "everyone": "大家:dàjiā",
        "to feel happy, to rejoice, to have a great time": "开心:kāixīn",
        "to dance": "跳舞:tiàowǔ",
        "famous": "有名:yǒumíng",
        "singer": "歌手:gēshǒu",
        "currency unit (esp. Chinese yuan)": "元:yuán",
        "as if, to seem like": "好像:hǎoxiàng",
        "bottoms up , Cheers.": "干杯:gānbēi",
        "to stay": "待:dāi",
        "to relax": "放松:fàngsōng",
        "to graduate": "毕业:bìyè",
        "to associate (with), to date, (interpersonal) relationship": "交往:jiāowǎng",
        "once, previously, ever, (past tense marker used before Verb or clause)": "曾经:céngjīng",
        "at once, right away, immediately": "马上:mǎshàng",
        "room": "房间:fángjiān",
        "cloudy": "阴天:yīn tiān",
        "kitchen": "厨房:chúfáng",
        "cake": "蛋糕:dàngāo",
        "to be hungry": "饿:è",
        "milk": "牛奶:niúnǎi",
        "to go out": "出去:chūqù",
        "game": "游戏:yóuxì",
        "quiet, peaceful, calm": "安静:ānjìng",
        "park": "公园:gōngyuán",
        "to discover": "发现:fāxiàn",
        "to cross the street": "过马路:guò mǎlù",
        "concentrated": "专心:zhuānxīn",
        "danger, dangerous": "危险:wēixiǎn",
        "news": "新闻:xīnwén",
        "Attractions, scenic spot, place of interest (tourism)": "景点:Jǐngdiǎn",
        "city": "城市:chéngshì",
        "building": "建筑:jiànzhù",
        "season": "季节:jìjié",
        "summer": "夏天:xiàtiān",
        "to line up , queue up": "排队:páiduì",
        "bustling with noise and excitement, lively": "热闹:rènào",
        "to bask in the sun": "晒太阳:shài tàiyáng",
        "dessert；sweet": "甜食:tiánshí",
        "health, healthy": "健康:jiànkāng",
        "Junk food": "垃圾食物:lājī shíwù",
        "to stay up late or all night": "熬夜:áoyè",
        "last year": "去年:qùnián",
        "love, to love": "爱:ài",
        "to lose weight": "减肥:jiǎnféi",
        "fat": "胖:pàng",
        "important, significant, major": "重要:zhòngyào",
        "to study abroad": "留学:liúxué",
        "friendly": "友好:yǒuhǎo",
        "Measure word for sealed objects, esp. letters": "封:fēng",
        "chopsticks": "筷子:kuàizi",
        "knife and fork": "刀叉:dāo chā",
        "Western": "西方:xīfāng",
        "a person's preferences, tastes (in food), flavor": "口味:kǒuwèi",
        "more or less,about the same": "差不多:chàbuduō",
        "same, like, equal to, the same as, just like": "一样:yíyàng",
        "wind": "风:fēng",
        "forecast": "预报:yùbào",
        "end of the month": "月底:yuèdǐ",
        "wet": "湿:shī",
        "dry": "干:gān",
        "to dislike, annoying": "讨厌:tǎoyàn",
        "temperature": "气温:qìwēn",
        "winter": "冬天:dōngtiān",
        "to hold up an umbrella": "打伞:dǎ sǎn",
        "to bring": "带:dài",
        "to welcome, welcome": "欢迎:huānyíng",
        "to move (i.e. relocate oneself), to move (something relatively heavy or bulky)": "搬:bān",
        "storied building, floor": "楼:lóu",
        "neighbor, next door": "邻居:línjū",
        "to help, to do a favor": "帮忙:bāngmáng",
        "flower": "花:huā",
        "to throw, to throw away": "扔:rēng",
        "wardrobe": "衣柜:yīguì",
        "furniture store": "家具店:jiājù diàn",
        "bed": "床:chuáng",
        "heavy": "重:zhòng",
        "to need,to demand, to require, requirement": "需要:xūyào",
        "to text, to send": "发:fā",
        "text message": "短信:duǎnxìn",
        "quality": "质量:zhìliàng",
        "to record, to note, to memorize": "记:jì",
        "notebook": "笔记本:bǐjìběn",
        "to remember": "记得:jìde",
        "if, in case": "如果:rúguǒ",
        "to propose, to suggest, suggestion, recommendation": "建议:jiànyì",
        "blackboard": "黑板:hēibǎn",
        "method, way": "方法:fāngfǎ",
        "to hang or suspend (from a hook etc)": "挂:guà",
        "to draw, painting": "画:huà",
        "living room": "客厅:kètīng",
        "window": "窗户:chuānghù",
        "sofa": "沙发:shāfā",
        "orderly, neat, even, tidy": "整齐:zhěngqí",
        "lamp, light, lantern": "灯:dēng",
        "chair": "椅子:yǐzi",
        "to put, to place": "放:fàng",
        "fish": "鱼:yú",
        "shrimp, prawn": "虾:xiā",
        "to cook, to boil": "煮:zhǔ",
        "beef": "牛肉:niúròu",
        "mutton, lamb meat": "羊肉:yángròu",
        "way of handling something, method for making, work method, recipe,": "做法:zuòfǎ",
        "measure word for tables of guests at a banquet etc": "桌:zhuō",
        "reason": "原因:yuányīn",
        "to pick up food with chopsticks": "夹:jiá",
        "to wrap (something in a bag), to load, to pack": "装:zhuāng",
        "to open, to turn on, to switch on": "打开:dǎkāi",
        "to hold, to seize, to catch, to take": "拿:ná",
        "luggage": "行李:xínglǐ",
        "pocket": "口袋:kǒudài",
        "water bottle": "水瓶:shuǐpíng",
        "coins": "钱币:qiánbì",
        "passport": "护照:hùzhào",
        "key": "钥匙:yàoshi",
        "visa": "签证:qiānzhèng",
        "airport": "机场:jīchǎng",
        "to see, to catch sight of": "看到:kàndào",
        "(long) time, (long) duration of time": "久:jiǔ",
        "probably, roughly, approximately, about,": "大概:dàgài",
        "so much, this much": "这么:zhème",
        "surely, certainly": "一定:yídìng",
        "to pick up (the phone), to answer (the phone)": "接:jiē",
        "empty": "空:kōng",
        "landlord": "房东:fángdōng",
        "tenant": "房客:fángkè",
        "transportation/traffic": "交通:jiāotōng",
        "assistance, aid, to help, to assist": "帮助:bāngzhù",
        "suitable, fitting": "合适:héshì",
        "to change, to switch": "换:huàn",
        "section of a room or lateral space between two pairs of pillars, Measure word for rooms": "间:jiān",
        "to make a noise, noisy": "吵:chǎo",
        "other, (something or somebody) else, the rest": "其他:qítā",
        "usually": "平常:píngcháng",
        "bathroom": "洗手间:xǐshǒujiān",
        "culture": "文化:wénhuà",
        "to be convinced (that something is true), to believe,": "相信:xiāngxìn",
        "opportunity, chance,": "机会:jīhuì",
        "to review": "复习:fùxí",
        "next time": "下次:xiàcì",
        "to understand, to comprehend": "懂:dǒng",
        "oneself/myself/ownself": "自己:zìjǐ",
        "Beijing Opera, Peking Opera": "京剧:jīngjù",
        "performance,perform": "表演:biǎoyǎn",
        "brilliant, marverlous": "精彩:jīngcǎi",
        "What's up?, What's going on?, What happened?": "怎么了？:zěnmele?",
        "to quarrel": "吵架:chǎojià",
        "complexion, look": "脸色:liǎnsè",
        "boyfriend": "男朋友:nánpéngyou",
        "to cry, to weep": "哭:kū",
        "to talk about": "谈一谈:tán yī tán",
        "ugly, unsightly": "难看:nánkàn",
        "happen, occur, take place": "发生:fāshēng",
        "misunderstanding, misunderstand": "误会:wùhuì",
        "computer": "电脑:diànnǎo",
        "Measure word for vehicles or machines": "台:tái",
        "to give a discount": "打折:dǎzhé",
        "to accompany, to keep somebody company": "陪:péi",
        "bank": "银行:yínháng",
        "parents": "父母:fùmǔ",
        "department store": "百货公司:bǎihuò gōngsī",
        "refrigerator": "冰箱:bīngxiāng",
        "second-hand (information, equipment etc)": "二手:èrshǒu",
        "original, former": "原来:yuánlái",
        "relaxed,to relaxed": "轻松:qīngsōng",
        "to set off, to start (on a journey)": "出发:chūfā",
        "history": "历史:lìshǐ",
        "modern times, modern age, modern era": "现代:xiàndài",
        "city center, downtown": "市中心:shì zhōngxīn",
        "to prohibit, to forbid, to ban": "禁止:jìnzhǐ",
        "to stroll, to visit": "逛:guàng",
        "style": "风格:fēnggé",
        "certainly, of course": "当然:dāngrán",
        "to lose the way, lost,": "迷路:mílù",
        "to get on or into (a bus, train, car etc)": "上车:shàng chē",
        "sunny day": "晴天:qíngtiān",
        "there's not enough time (to do something), it's too late (to do something)": "来不及:láibují",
        "then, after that": "然后:ránhòu",
        "at once, immediately": "赶快:gǎnkuài",
        "to get off or out of (a bus, train, car etc)": "下车:xiàchē",
        "hurried, to make (somebody) anxious": "急:jí",
        "to do, to manage, to handle, to play with, to fool with, to mess with, to fix, to toy with": "弄:nòng",
        "bad, spoiled, broken, to break down": "坏:huài",
        "to get angry, angry": "生气:shēngqì",
        "heedless, careless": "不小心:bù xiǎoxīn",
        "to move (house)": "搬家:bānjiā",
        "to treat, to invite to dinner": "请客:qǐngkè",
        "to arrange, to tidy up": "整理:zhěnglǐ",
        "to sweep the floor,": "扫地:sǎodì",
        "to break, to smash": "打破:dǎpò",
        "to lose": "丢:diū",
        "to have an accident, to meet with a mishap": "出事:chūshì",
        "strange, odd": "奇怪:qíguài",
        "muddled, silly, confused": "糊涂:hútú",
        "to have disappeared, to be missing": "不见:bújiàn",
        "to feel sad, to feel unwell": "难过:nánguò",
        "luckily, fortunately": "好在:hǎo zài",
        "Dont rush, dont be anxious": "别急:bié jí",
        "thief": "小偷:xiǎotōu",
        "to steal": "偷:tōu",
        "to put on or wear (glasses, hat, gloves etc)": "戴:dài",
        "to carry on the back or shoulder": "背:bēi",
        "hat, cap": "帽子:màozi",
        "spectacles, eyeglasses": "眼镜:yǎnjìng",
        "knapsack,backpack": "背包:bèibāo",
        "shoes": "鞋:xié",
        "shirt, blouse": "衬衫:chènshān",
        "trousers, pants": "裤子:kùzi",
        "a pair of": "双:shuāng",
        "to run": "跑:pǎo",
        "police, police officer": "警察:jǐngchá",
        "no wonder!, so that's why!": "怪不得:guàibùdé",
        "approximately": "左右:zuǒyòu",
        "competition (sports etc), match": "比赛:bǐsài",
        "to beat, to win": "赢:yíng",
        "to score a goal": "进球:jìn qiú",
        "bald": "秃:tū",
        "charming": "魅力:mèilì",
        "sports star (ball sport)": "球星:qiúxīng",
        "to pass": "经过:jīngguò",
        "round shape": "圆:yuán",
        "husband": "丈夫:zhàngfu",
        "measure word for people (honorific)": "位:wèi",
        "eye": "眼睛:yǎnjīng",
        "wife": "妻子:qīzi",
        "face": "脸:liǎn",
        "height, stature": "个子:gèzi",
        "Mr., husband": "先生:xiānsheng",
        "almost, nearly": "差不多:chàbùduō",
        "tremendous, awesome": "厉害:lìhài",
        "listening skill/ hearing": "听力:tīnglì",
        "great effort, to try hard": "努力:nǔlì",
        "to improve, to get ahead": "进步:jìnbù",
        "nervous": "紧张:jǐnzhāng",
        "difficult": "难:nán",
        "easy": "容易:róngyì",
        "to pass": "过:guò",
        "to understand, to realize": "明白:míngbái",
        "to believe, to think": "认为:rènwéi",
        "auspicious, lucky, propitious": "吉利:jílì",
        "to get rich": "发财:fācái",
        "number": "数字:shùzì",
        "meaning": "意思:yìsi",
        "friendship": "友谊:yǒuyì",
        "to live, alive": "活:huó",
        "to have a date": "约会:yuēhuì",
        "to place an order, to book ahead": "预订:yùdìng",
        "restaurant": "餐厅:cāntīng",
        "on time, punctual, on schedule": "准时:zhǔnshí",
        "to laugh, to smile": "笑:xiào",
        "doorway, gate": "门口:ménkǒu",
        "Measure word for families or businesses,": "家:jiā",
        "Valentine's Day": "情人节:qíngrén jié",
        "(used after a verb) in a while, give it a try": "一下儿:yīxià er",
        "to celebrate": "庆祝:qìngzhù",
        "colleague, co-worker": "同事:tóngshì",
        "to find": "找到:zhǎodào",
        "congratulations": "恭喜:gōngxǐ",
        "to finish work, to get off work": "下班:xiàbān",
        "environment, circumstances, surroundings": "环境:huánjìng",
        "tour guide": "导游:dǎoyóu",
        "culinary delicacy, fine food": "美食:měishí",
        "to read a book, to study, to attend school": "读书:dúshū",
        "magazine": "杂志:zázhì",
        "to recline, to lie down": "躺:tǎng",
        "to fall asleep": "睡着:shuìzháo",
        "to cough": "咳嗽:késou",
        "in the end": "结果:jiéguǒ",
        "whole": "整个:zhěnggè",
        "how terrible, what bad luck, terrible, bad": "糟糕:zāogāo",
        "to be touched (somebody emotionally)": "感动:gǎndòng",
        "regret, to regret, to be sorry that": "遗憾:yíhàn",
        "to meet, to see each other": "见面:jiànmiàn",
        "party, gathering": "聚会:jùhuì",
        "to get in touch with, to contact, to link": "联系:liánxì",
        "to be sorry, to feel apologetic": "抱歉:bàoqiàn",
        "to prepare": "准备:zhǔnbèi",
        "surprise": "惊喜:jīngxǐ",
        "purse, wallet": "钱包:qiánbāo",
        "color": "颜色:yánsè",
        "service desk, information desk, reception desk": "服务台:fúwùtái",
        "ID": "证件:zhèngjiàn",
        "cash": "现金:xiànjīn",
        "to take away": "拿走:názǒu",
        "credit card": "信用卡:xìnyòngkǎ",
        "to receive": "收到:shōudào",
        "address": "地址:dìzhǐ",
        "to send": "寄:jì",
        "package": "包裹:bāoguǒ",
        "sweater": "毛衣:máoyī",
        "to test, to try": "试:shì",
        "case/box": "盒子:hézi",
        "to take note of, to pay attention to": "注意:zhùyì",
        "to take care of, to show consideration, to attend to, to look after": "照顾:zhàogù",
        "vigor, vitality, drive, spiritual": "精神:jīngshen",
        "physical strength, physical power": "体力:tǐlì",
        "influence, effect, to influence, to affect (usually adversely), to disturb": "影响:yǐngxiǎng",
        "school assignment, homework,": "作业:zuòyè",
        "kung fu": "功夫:gōngfu",
        "to wake up, to get up": "起来:qǐlái",
        "to wish for, to desire, hope": "希望:xīwàng",
        "to avail oneself of, to take advantage of": "趁:chèn",
        "day, a (calendar) date, days of one's life": "日子:rìzi",
        "to continue, to proceed with, to go on with": "继续:jìxù",
        "like this, this way": "这样:zhèyàng",
        "to leave, to bid farewell to, to say good-bye to": "告别:gàobié",
        "(there are) some (who are...), some (exist)": "有的:yǒude",
        "to see off": "送:sòng",
        "towards": "向:xiàng",
        "farewell party, going away party": "欢送会:huānsònghùi",
        "to marry, to get married": "结婚:jiéhūn",
        "totally, entirely": "完全:wánquán",
        "to fall, to collapse,": "倒:dǎo",
        "legend, folklore, tradition": "传说:chuánshuō",
        "to build, to construct": "建:jiàn",
        "to grab, to catch, to arrest": "抓:zhuā",
        "whole nation, nationwide": "全国:quánguó",
        "the Great Wall": "长城:chángchéng",
        "story, tale": "故事:gùshì",
        "a bit": "一下:yīxià",
        "and also": "也:yě",
        "again, once more": "再:zài",
        "out, outer, outside": "出:chū",
        "do not, don't do sth.": "别:bié",
        "to sell": "卖:mài",
        "to be able to, can": "可以:kěyǐ",
        "right, right side": "右边:yòubiān",
        "Right now": "吧:ba",
        "Because Therefore…": "因为…所以…:yīnwèi…suǒyǐ…",
        "outer, outside": "外:wài",
        "female, feminine": "女:nǚ",
        "it": "它:tā",
        "to finish": "完:wán",
        "hotel, guest house, lodge": "宾馆:bīnguǎn",
        "Correct": "对:duì",
        "left, left side": "左边:zuǒbiān",
        "to": "往:wǎng",
        "you (polite form)": "您:nín",
        "watch, a wristwatch": "手表:shǒubiǎo",
        "to play basketball": "打篮球:dǎ lánqiú",
        "to find": "找:zhǎo",
        "classroom": "教室:jiàoshì",
        "morning": "早上:zǎoshang",
        "clear, sunny": "晴:qíng",
        "Is on": "正在:zhèngzài",
        "each, every": "每:měi",
        "ratio": "比:bǐ",
        "to wash, to clean": "洗:xǐ",
        "train station": "火车站:huǒchēzhàn",
        "to play, to have fun, to hang out": "玩:wán",
        "man, male, masculine": "男:nán",
        "an action currently happening , -ing": "着:zhe",
        "ticket": "票:piào",
        "from": "离:lí",
        "to wear, to dress": "穿:chuān",
        "the first, 1st, number one": "第一:dì yī",
        "red": "红:hóng",
        "However, although…": "虽然…但是…:suīrán…dànshì…",
        "watermelon": "西瓜:xīguā",
        "to let, make, allow, cause": "让:ràng",
        "expensive": "贵:guì",
        "to run": "跑步:pǎobù",
        "to play soccer": "踢足球:tīzúqiú",
        "also, or": "还:hái",
        "to enter": "进:jìn",
        "pencil": "铅笔:qiānbǐ",
        "wrong, to wrong, to err, error, mistake": "错:cuò",
        "door": "门:mén",
        "to ask, to inquire": "问:wèn",
        "cloudy": "阴:yīn",
        "snow": "雪:xuě",
        "zero": "零:líng",
        "noodles": "面条:miàntiáo",
        "black": "黑:hēi",
        "to dream": "做梦:zuòmèng",
        "to call": "叫:jiào",
        "That's right!": "没错:méicuò",
        "to despise, to underestimate": "小看:xiǎokàn",
        "deal": "说定了:shuō dìng le",
        "soup": "汤:tāng",
        "show": "露一手:lòuyìshǒu",
        "to raise, to bring up, to cultivate": "养:yǎng",
        "finally": "终于:zhōngyú",
        "to feel relived, to feel reassured, to be at ease": "放心:fàngxīn",
        "to register, to sign up": "报名:bàomíng",
        "to dare": "敢:gǎn",
        "to be afraid": "害怕:hàipà",
        "street": "街道:jiēdào",
        "measure word for car": "辆:liàng",
        "driver's license": "驾照:jiàzhào",
        "original, at first": "原来:yuánlái",
        "ticket (for theater, cinema etc)": "门票:ménpiào",
        "cost": "费用:fèiyòng",
        "insurance": "保险:bǎoxiǎn",
        "traveler, tourist": "游客:yóukè",
        "to be overdue, to exceed the time limit, to expire": "过期:guòqī",
        "travel agency": "旅行社:lǚxíngshè",
        "places of historic interest, historical sites": "古迹:gǔjì",
        "Asia": "亚洲:Yàzhōu",
        "tour group": "旅行团:lǚxíng tuán",
        "place, site, location, venue": "地点:dìdiǎn",
        "Europe": "欧洲:Ōuzhōu",
        "Italy": "意大利:Yìdàlì",
        "Germany": "德国:Déguó",
        "characteristic, distinguishing feature or quality": "特色:tèsè",
        "to arrange, to plan, to set up, arrangements, plans": "安排:ānpái",
        "itinerary": "行程:xíngchéng",
        "climate": "气候:qìhòu",
        "for example": "比如说:bǐrú shuō",
        "one of something": "之一:zhīyī",
        "ancient, old": "古老:gǔlǎo",
        "to participate, to attend": "参加:cānjiā",
        "Spain": "西班牙:Xībānyá",
        "contract": "合同:hétóng",
        "specialized field, main field of study (at university), major": "专业:zhuānyè",
        "to notify, to inform, notice, notification": "通知:tōngzhī",
        "to agree, to consent, to approve": "同意:tóngyì",
        "to be, to act as": "当:dāng",
        "news, information": "消息:xiāoxi",
        "to be worried; to be distressed; worries": "烦恼:fánnǎo",
        "development; growth; to develop; to grow; to expand": "发展:fāzhǎn",
        "to catch cold; (common) cold": "感冒:gǎnmào",
        "to give or have an injection": "打针:dǎzhēn",
        "serious": "严重:yánzhòng",
        "to have a high temperature (from illness); to have a fever": "发烧:fāshāo",
        "to feel unwell; to suffer pain; to be difficult to bear": "难受:nánshòu",
        "inspection; to examine; to inspect": "检查:jiǎnchá",
        "throat; voice": "嗓子:sǎngzi",
        "to stay up late": "晚睡:wǎnshuì",
        "to worry; to feel anxious": "着急:zháojí",
        "to work a temporary or casual job; (of students) to have a job outside of class time, or during vacation": "打工:dǎgōng",
        "to earn money": "赚钱:zhuànqián",
        "educational background; academic qualifications": "学历:xuélì",
        "to hire": "请:qǐng",
        "simple; not complicated": "简单:jiǎndān",
        "to decide (to do something); to resolve; decision; certainly": "决定:juédìng",
        "to suffer": "吃苦头:chī kǔtou",
        "do business": "做生意:zuò shēngyì",
        "meaningful": "有意义:yǒu yìyì",
        "male addicted to computers, computer games, adult cartoons etc": "宅男:zháinán",
        "all day long; whole day": "整天:zhěng tiān",
        "interest; hobby": "爱好:àihào",
        "frequently; constantly; regularly; often; day-to-day; everyday; daily": "经常:jīngcháng",
        "to go; take out (relates to food bought at a restaurant)": "外卖:wàimài",
        "to enjoy; to live it up; pleasure": "享受:xiǎngshòu",
        "lively": "活泼:huópō",
        "outdoor": "户外:hùwài",
        "activity": "活动:huódòng",
        "holiday, non-working day": "假日:jiàrì",
        "roommate": "同屋:tóngwū",
        "to make friends": "交:jiāo",
        "to meet": "遇到:yùdào",
        "by chance, by coincidence, to happen to": "好巧:hǎo qiǎo",
        "exchange students": "交换学生:jiāohuàn xuésheng",
        "dorm room": "宿舍:sùshè",
        "to be familiar with, to know well": "熟悉:shúxī",
        "cordial, enthusiastic, passion, passionate, passionately": "热情:rèqíng",
        "attire, clothes, dress": "穿着:chuānzhuó",
        "to dress, to make up": "打扮:dǎbàn",
        "to change, to become different, to transform": "变:biàn",
        "fashionable": "时髦:shímáo",
        "to feel, to sense, to have the feeling that": "感到:gǎndào",
        "price": "价钱:jiàqián",
        "vacation": "假期:jiàqī",
        "beach, sandy shore": "沙滩:shātān",
        "swimming pool": "游泳池:yóuyǒngchí",
        "unforgettable": "难忘:nánwàng",
        "south": "南:nán",
        "north": "北:běi",
        "east": "东:dōng",
        "west": "西:xi",
        "benefit, advantage": "好处:hǎochu",
        "interest, hobby": "兴趣:xìngqù",
        "to engage in physical exercise, to work out": "锻炼:duànliàn",
        "gym": "健身房:jiànshēnfáng",
        "to climb a mountain": "登山:dēngshān",
        "to choose, to pick, to select, to elect, choice": "选择:xuǎnzé",
        "harm, disadvantage": "坏处:huàichu",
        "to persevere with, to persist in": "坚持:jiānchí",
        "to complete, to accomplish": "完成:wánchéng",
        "must, need to, have to": "必须:bìxū",
        "but, however, only, merely": "不过:bùguò",
        "just now": "刚才:gāngcái",
        "midnight": "半夜:bànyè",
        "to apply for job": "应征:yìngzhēng",
        "commercial, advertise": "广告:guǎnggào",
        "everywhere": "到处:dàochù",
        "easy": "容易:róngyì",
        "clear, to understand": "清楚:qīngchu",
        "the first step, step one": "第一步:dì yībù",
        "the next step, then": "下一步:xià yī bù",
        "fry (meat, fish, or vegetables) rapidly over a high heat while stirring briskly": "炒:chǎo",
        "tomato": "西红柿:xīhóngshì",
        "recipe": "食谱:shípǔ",
        "upside down, pour, collapse, fail": "倒:dào",
        "oil, fat": "油:yóu",
        "courses in a meal": "道:dào",
        "greasy, oily": "油腻:yóunì",
        "salt": "盐:yán",
        "light, weak, delicate, mild": "清淡:qīngdàn",
        "to cut": "切:qiē",
        "to get": "得:dé",
        "symtom": "症状:zhèngzhuàng",
        "nothing serious, doesn't matter,Never mind": "没事:méishì",
        "(body)temperature": "体温:tǐwēn",
        "to measure": "量:liáng",
        "useless": "没用:méiyòng",
        "serious, important , critical": "要紧:yàojǐn",
        "necessary": "必要:bìyào",
        "to delay": "耽误:dānwù",
        "to stop, to halt, to freeze": "站住:zhànzhù",
        "solution, method, way": "办法:bànfǎ",
        "to understand, to find out": "了解:liǎojiě",
        "autumn, fall": "秋天:qiūtiān",
        "young": "年轻:niánqīng",
        "problem, question, issue, matter": "问题:wèntí",
        "to solve, to settle": "解决:jiějué",
        "businessman": "生意人:shēngyì rén",
        "dirty, dishonest": "黑心:hēixīn",
        "all family": "全家:quánjiā",
        "to report（an incident）to the police": "报警:bàojǐng",
        "failure, to fail": "失败:shībài",
        "rare, hard": "难得:nándé",
        "maybe": "也许:yěxǔ",
        "to park": "停:tíng",
        "always": "总是:zǒngshì",
        "full (to eat till full)": "饱:bǎo",
        "to find time to do something": "抽空:chōukòng",
        "king": "国王:guówáng",
        "previous": "从前:cóngqián",
        "animal": "动物:dòngwù",
        "elephant": "大象:dàxiàng",
        "curious": "好奇:hàoqí",
        "mark": "记号:jìhào",
        "to draw, painting": "画:huà",
        "boat": "船:chuán",
        "idea": "主意:zhǔyi",
        "to sink": "下沉:xiàchén",
        "popular, fashionable": "流行:liúxíng",
        "to dress up, to make up , dress, way or style of dressing": "打扮:dǎbàn",
        "green": "绿:lǜ",
        "to match": "配:pèi",
        "purple": "紫:zǐ",
        "to worry about": "操心:cāoxīn",
        "charm": "魅力:mèilì",
        "to care about": "在乎:zàihu",
        "dream, ideal": "理想:lǐxiǎng",
        "driver": "司机:sījī",
        "diplomat": "外交官:wàijiāo guān",
        "pay, wages": "工资:gōngzī",
        "to stay, leave behind": "留:liú",
        "nurse": "护士:hùshì",
        "for": "为:wèi",
        "service": "服务:fúwù",
        "desire, wish": "愿望:yuànwàng",
        "to fulfil, to come true": "实现:shíxiàn",
        "to hide the truth from": "瞒:mán",
        "only daughter": "独生女:dúshēngnǚ",
        "free, freedom": "自由:zìyóu",
        "to consult, to discuss": "商量:shāngliáng",
        "truth": "实话:shíhuà",
        "to leave, to depart": "离别:líbié",
        "online": "网上:wǎngshàng",
        "to shop (shopping)": "购物:gòuwù",
        "to withdraw (a product)": "退:tuì",
        "reliable, trustworthy": "可靠:kěkào",
        "brand": "牌子:páizi",
        "to try wearing clothes, fitting trial": "试穿:shìchuān",
        "products": "用品:yòngpǐn",
        "inferior": "差:chà",
        "bank account": "户头:hùtóu",
        "to do, to handle, to manage": "办:bàn",
        "procedures": "手续:shǒuxù",
        "to transfer account": "转账:zhuǎnzhàng",
        "automatically": "自动:zìdòng",
        "receipt": "收据:shōujù",
        "to pay a fee": "缴费:jiǎofèi",
        "to verbally abuse , call names": "骂:mà",
        "to think over, to consider": "考虑:kǎolǜ",
        "to recommend": "推荐:tuījiàn",
        "it is a pity, what a pity, unfortunately": "可惜:kěxī",
        "worthwhile, value for money, to view as profitable": "划算:huásuàn",
        "to guarantee, to assure": "保证:bǎozhèng",
        "headphones, earphones, telephone receiver": "耳机:ěrjī",
        "to repair, to build": "修:xiū",
        "waterproof": "防水:fángshuǐ",
        "to request, to require, the other party's wishes and conditions": "要求:yāoqiú",
        "suggestion": "意见:yìjiàn",
        "situation": "情况:qíngkuàng",
        "elder family members": "长辈:zhǎngbèi",
        "younger family members": "晚辈:wǎnbèi",
        "each": "各:gè",
        "last generation": "上一代:shàngyídài",
        "background": "背景:bèijǐng",
        "to sum up, overall": "总之:zǒngzhī",
        "opinion": "想法:xiǎngfǎ",
        "fortunately, luckily": "幸亏:xìngkuī",
        "grave, serious, severe, critical": "严重:yánzhòng",
        "to sustain injuries, be wounded, be harmed (in an accident etc)​": "受伤:shòushāng",
        "to bump into, to hit": "撞到:zhuàngdào",
        "tree": "树:shù",
        "accident": "事故:shìgù",
        "ambulance": "救护车:jiùhùchē",
        "classifier for trees, cabbages, plants etc": "棵:kē",
        "voice, sound": "声音:shēngyīn",
        "to dye": "染:rǎn",
        "eye-catching": "醒目:xǐngmù",
        "private life": "私生活:sī shēnghuó",
        "to intervene": "干涉:gānshè",
        "to concede, concession": "让步:ràngbù",
        "to get sick because of bad food": "吃坏肚子:chī huài dùzi",
        "fresh": "新鲜:xīnxiān",
        "to have diarrhea": "拉肚子:lādùzi",
        "painful": "疼:téng",
        "emergency": "急诊:jízhěn",
        "to inject": "打针:dǎzhēn",
        "cooked, done": "熟:shú",
        "lamb meat": "羊肉:yángròu",
        "sea food": "海鲜:hǎixiān",
        "watch": "表:biǎo",
        "a unit that calculates blocks or pieces": "块:kuài",
        "style, type": "样式:yàngshì",
        "here": "这边:zhè biān",
        "famous and valuable, rare, precious": "名贵:míngguì",
        "to pack, to package": "包装:bāozhuāng",
        "to produce": "产:chǎn",
        "to be willing to": "愿意:yuànyì",
  
        }

        static getWords(){
                return MyChineseWords.words;
        }
}

export default MyChineseWords;