

class MyVietnameseWords  {
   static words = {
        "as": "như",
        "I": "tôi",
        "his": "mình",
        "that": "mà",
        "he": "ông",
        "was": "là",
        "for": "cho",
        "on": "trên",
        "are": "là",
        "with": "với",
        "they": "họ",
        "be": "được",
        "at": "tại",
        "one": "một",
        "have": "có",
        "this": "này",
        "from": "từ",
        "by": "bởi",
        "hot": "nóng",
        "word": "từ",
        "but": "nhưng",
        "what": "những gì",
        "some": "một số",
        "is": "là",
        "it": "nó",
        "you": "anh",
        "or": "hoặc",
        "had": "có",
        "the": "các",
        "of": "của",
        "to": "để",
        "and": "và",
        "a": "một",
        "in": "trong",
        "we": "chúng tôi",
        "can": "có thể",
        "out": "ra",
        "other": "khác",
        "were": "là",
        "which": "mà",
        "do": "làm",
        "their": "của họ",
        "time": "thời gian",
        "if": "nếu",
        "will": "sẽ",
        "how": "như thế nào",
        "said": "nói",
        "an": "một",
        "each": "môi",
        "tell": "nói",
        "does": "không",
        "set": "bộ",
        "three": "ba",
        "want": "muốn",
        "air": "không khí",
        "well": "cũng",
        "also": "cũng",
        "play": "chơi",
        "small": "nhỏ",
        "end": "cuối",
        "put": "đặt",
        "home": "nhà",
        "read": "đọc",
        "hand": "tay",
        "port": "cổng",
        "large": "lớn",
        "spell": "chính tả",
        "add": "thêm",
        "even": "thậm chí",
        "land": "đất",
        "here": "ở đây",
        "must": "phải",
        "big": "lớn",
        "high": "cao",
        "such": "như vậy",
        "follow": "theo",
        "act": "hành động",
        "why": "lý do tại sao",
        "ask": "xin",
        "men": "người đàn ông",
        "change": "thay đổi",
        "went": "đi",
        "light": "ánh sáng",
        "kind": "loại",
        "off": "tắt",
        "need": "cần",
        "house": "nhà",
        "picture": "hình ảnh",
        "try": "thử",
        "us": "chúng tôi",
        "again": "một lần nữa",
        "animal": "động vật",
        "point": "điểm",
        "mother": "mẹ",
        "world": "thế giới",
        "near": "gần",
        "build": "xây dựng",
        "self": "tự",
        "earth": "đất",
        "father": "cha",
        "any": "bất kỳ",
        "new": "mới",
        "work": "công việc",
        "part": "một phần",
        "take": "có",
        "get": "được",
        "place": "nơi",
        "made": "thực hiện",
        "live": "sống",
        "where": "nơi",
        "after": "sau khi",
        "back": "trở lại",
        "little": "ít",
        "only": "chỉ",
        "round": "chung quanh",
        "man": "người đàn ông",
        "year": "năm",
        "came": "đến",
        "show": "chương trình",
        "every": "mỗi",
        "good": "tốt",
        "me": "tôi",
        "give": "cung cấp cho",
        "our": "của chúng tôi",
        "under": "dưới",
        "name": "tên",
        "very": "rất",
        "through": "thông qua",
        "just": "chỉ",
        "form": "hình thức",
        "sentence": "câu",
        "great": "tuyệt vời",
        "think": "nghi",
        "say": "nói",
        "help": "giúp",
        "low": "thấp",
        "line": "dòng",
        "differ": "khác nhau",
        "turn": "lần lượt",
        "cause": "nguyên nhân",
        "much": "nhiều",
        "mean": "có nghĩa là",
        "before": "trước",
        "move": "di chuyển",
        "right": "ngay",
        "boy": "cậu bé",
        "old": "cũ",
        "too": "quá",
        "same": "như nhau",
        "she": "cô",
        "all": "tất cả",
        "there": "có",
        "when": "khi",
        "up": "lên",
        "use": "sử dụng",
        "your": "của bạn",
        "way": "cách",
        "about": "về",
        "many": "nhiều",
        "then": "sau đó",
        "them": "họ",
        "write": "viết",
        "would": "sẽ",
        "like": "như",
        "so": "để",
        "these": "các",
        "her": "cô",
        "long": "lâu",
        "make": "làm",
        "thing": "điều",
        "see": "thấy",
        "him": "anh",
        "two": "hai",
        "has": "có",
        "look": "xem",
        "more": "hơn",
        "day": "ngày",
        "could": "có thể",
        "go": "đi",
        "come": "đến",
        "did": "đã làm",
        "number": "số",
        "sound": "âm thanh",
        "no": "không có",
        "most": "nhất",
        "people": "nhân dân",
        "my": "của tôi",
        "over": "hơn",
        "know": "biết",
        "water": "nước",
        "than": "hơn",
        "call": "gọi",
        "first": "đầu tiên",
        "who": "người",
        "may": "có thể",
        "down": "xuống",
        "side": "bên",
        "been": "được",
        "now": "bây giờ",
        "find": "tìm",
        "head": "đầu",
        "stand": "đứng",
        "own": "riêng",
        "page": "trang",
        "should": "nên",
        "country": "nước",
        "found": "tìm thấy",
        "answer": "câu trả lời",
        "school": "trường",
        "grow": "phát triển",
        "study": "nghiên cứu",
        "still": "vẫn",
        "learn": "học",
        "plant": "nhà máy",
        "cover": "bìa",
        "food": "thực phẩm",
        "sun": "ánh nắng mặt trời",
        "four": "bốn",
        "between": "giữa",
        "state": "nhà nước",
        "keep": "giữ",
        "eye": "mắt",
        "never": "không bao giờ",
        "last": "cuối cùng",
        "let": "cho phép",
        "thought": "nghĩ",
        "city": "thành phố",
        "tree": "cây",
        "cross": "qua",
        "farm": "trang trại",
        "hard": "cứng",
        "start": "bắt đầu",
        "might": "might",
        "story": "câu chuyện",
        "saw": "cưa",
        "far": "đến nay",
        "sea": "biển",
        "draw": "vẽ",
        "left": "còn lại",
        "late": "cuối",
        "run": "chạy",
        "don’t": "không",
        "while": "trong khi",
        "press": "báo chí",
        "close": "gần",
        "night": "đêm",
        "real": "thực",
        "life": "cuộc sống",
        "few": "số",
        "north": "phía bắc",
        "book": "cuốn sách",
        "carry": "thực hiện",
        "took": "mất",
        "science": "khoa học",
        "eat": "ăn",
        "room": "phòng",
        "friend": "người bạn",
        "began": "bắt đầu",
        "idea": "ý tưởng",
        "fish": "cá",
        "mountain": "núi",
        "stop": "ngăn chặn",
        "once": "một lần",
        "base": "cơ sở",
        "hear": "nghe",
        "horse": "ngựa",
        "cut": "cắt",
        "sure": "chắc chắn",
        "watch": "xem",
        "color": "màu",
        "face": "khuôn mặt",
        "wood": "gỗ",
        "main": "chính",
        "open": "mở",
        "seem": "dường như",
        "together": "cùng",
        "next": "tiếp theo",
        "white": "trắng",
        "children": "trẻ em",
        "begin": "bắt đầu",
        "got": "có",
        "walk": "đi bộ",
        "example": "Ví dụ",
        "ease": "giảm bớt",
        "paper": "giấy",
        "group": "nhóm",
        "always": "luôn luôn",
        "music": "nhạc",
        "those": "những",
        "both": "cả hai",
        "mark": "đánh dấu",
        "often": "thường",
        "letter": "thư",
        "until": "cho đến khi",
        "mile": "dặm",
        "river": "sông",
        "car": "xe",
        "feet": "chân",
        "care": "chăm sóc",
        "second": "thứ hai",
        "enough": "đủ",
        "plain": "đồng bằng",
        "girl": "cô gái",
        "usual": "thông thường",
        "young": "trẻ",
        "ready": "sẵn sàng",
        "above": "trên đây",
        "ever": "bao giờ",
        "red": "màu đỏ",
        "list": "danh sách",
        "though": "mặc dù",
        "feel": "cảm thấy",
        "talk": "nói chuyện",
        "bird": "chim",
        "soon": "sớm",
        "body": "cơ thể",
        "dog": "con chó",
        "family": "gia đình",
        "direct": "trực tiếp",
        "pose": "đặt ra",
        "leave": "lại",
        "song": "bài hát",
        "measure": "đo lường",
        "door": "cửa",
        "product": "sản phẩm",
        "black": "đen",
        "short": "ngắn",
        "numeral": "chữ số",
        "class": "lớp",
        "wind": "gió",
        "question": "câu hỏi",
        "happen": "xảy ra",
        "complete": "hoàn thành",
        "ship": "tàu",
        "area": "khu vực",
        "half": "một nửa",
        "rock": "đá",
        "order": "để",
        "fire": "lửa",
        "south": "nam",
        "problem": "vấn đề",
        "piece": "mảnh",
        "told": "nói",
        "knew": "biết",
        "pass": "vượt qua",
        "since": "từ",
        "top": "đầu",
        "whole": "toàn bộ",
        "king": "vua",
        "street": "đường phố",
        "inch": "inch",
        "multiply": "nhân",
        "nothing": "không có gì",
        "course": "Tất nhiên",
        "stay": "ở lại",
        "wheel": "bánh xe",
        "full": "đầy đủ",
        "force": "lực",
        "blue": "màu xanh",
        "object": "đối tượng",
        "decide": "quyết định",
        "surface": "bề mặt",
        "deep": "sâu",
        "moon": "mặt trăng",
        "island": "đảo",
        "foot": "chân",
        "system": "hệ thống",
        "busy": "bận rộn",
        "test": "kiểm tra",
        "record": "ghi",
        "boat": "thuyền",
        "common": "phổ biến",
        "gold": "vàng",
        "possible": "có thể",
        "plane": "máy bay",
        "stead": "thay",
        "dry": "khô",
        "wonder": "tự hỏi",
        "laugh": "cười",
        "thousand": "ngàn",
        "ago": "trước",
        "ran": "ran",
        "check": "kiểm tra",
        "game": "trò chơi",
        "shape": "hình dạng",
        "equate": "đánh đồng",
        "hot": "nóng",
        "miss": "bỏ lỡ",
        "brought": "mang",
        "heat": "nhiệt",
        "snow": "tuyết",
        "tire": "lốp xe",
        "bring": "mang lại",
        "yes": "vâng",
        "distant": "xa",
        "fill": "điền",
        "east": "đông",
        "paint": "sơn",
        "language": "ngôn ngữ",
        "among": "trong",
        "unit": "đơn vị",
        "power": "điện",
        "town": "thị trấn",
        "fine": "tốt",
        "certain": "nhất định",
        "fly": "bay",
        "fall": "giảm",
        "lead": "dẫn",
        "cry": "kêu",
        "dark": "tối",
        "machine": "máy",
        "note": "ghi",
        "wait": "đợi",
        "plan": "kế hoạch",
        "figure": "con số",
        "star": "sao",
        "box": "hộp",
        "noun": "danh từ",
        "field": "lĩnh vực",
        "rest": "phần còn lại",
        "correct": "chính xác",
        "able": "thể",
        "pound": "bảng",
        "done": "Xong",
        "beauty": "vẻ đẹp",
        "drive": "ổ đĩa",
        "stood": "đứng",
        "contain": "chứa",
        "front": "trước",
        "teach": "dạy",
        "week": "tuần",
        "final": "thức",
        "gave": "đã",
        "green": "màu xanh lá cây",
        "oh": "oh",
        "quick": "nhanh chóng",
        "develop": "phát triển",
        "ocean": "đại dương",
        "warm": "ấm áp",
        "free": "miễn phí",
        "minute": "phút",
        "strong": "mạnh mẽ",
        "special": "đặc biệt",
        "mind": "tâm",
        "behind": "sau",
        "clear": "trong",
        "tail": "đuôi",
        "produce": "sản xuất",
        "fact": "thực tế",
        "space": "không gian",
        "heard": "nghe",
        "best": "tốt nhất",
        "hour": "giờ",
        "better": "tốt hơn",
        "TRUE": "đúng",
        "during": "trong khi",
        "hundred": "trăm",
        "five": "năm",
        "remember": "nhớ",
        "step": "bước",
        "early": "đầu",
        "hold": "giư",
        "west": "tây",
        "ground": "mặt đất",
        "interest": "quan tâm",
        "reach": "đạt",
        "fast": "nhanh chóng",
        "verb": "động từ",
        "sing": "hát",
        "listen": "lắng nghe",
        "six": "sáu",
        "table": "bảng",
        "travel": "du lịch",
        "less": "ít",
        "morning": "buổi sáng",
        "ten": "mười",
        "simple": "đơn giản",
        "several": "nhiều",
        "vowel": "nguyên âm",
        "toward": "hướng",
        "war": "chiến tranh",
        "lay": "đặt",
        "against": "chống lại",
        "pattern": "mô hình",
        "slow": "chậm",
        "center": "trung tâm",
        "love": "tình yêu",
        "person": "người",
        "money": "tiền",
        "serve": "phục vụ",
        "appear": "xuất hiện",
        "road": "đường",
        "map": "Bản đồ",
        "rain": "mưa",
        "rule": "quy tắc",
        "govern": "phối",
        "pull": "kéo",
        "cold": "lạnh",
        "notice": "thông báo",
        "voice": "giọng nói",
        "energy": "năng lượng",
        "hunt": "săn",
        "probable": "có thể xảy ra",
        "bed": "giường",
        "brother": "anh trai",
        "egg": "trứng",
        "ride": "đi xe",
        "cell": "pin",
        "believe": "tin",
        "perhaps": "có lẽ",
        "pick": "chọn",
        "sudden": "đột ngột",
        "count": "tính",
        "square": "vuông",
        "reason": "lý do",
        "length": "chiều dài",
        "represent": "đại diện",
        "art": "nghệ thuật",
        "subject": "Tiêu đề",
        "region": "khu",
        "size": "kích thước",
        "vary": "khác nhau",
        "settle": "giải quyết",
        "speak": "nói",
        "weight": "trọng lượng",
        "general": "chung",
        "ice": "băng",
        "matter": "vấn đề",
        "circle": "vòng tròn",
        "pair": "đôi",
        "include": "bao gồm",
        "divide": "chia",
        "syllable": "âm tiết",
        "felt": "cảm thấy",
        "grand": "lớn",
        "ball": "bóng",
        "yet": "nhưng",
        "wave": "sóng",
        "drop": "rơi",
        "heart": "tim",
        "am": "là",
        "present": "hiện nay",
        "heavy": "nặng",
        "dance": "khiêu vũ",
        "engine": "động cơ",
        "position": "vị trí",
        "arm": "cánh tay",
        "wide": "rộng",
        "sail": "buồm",
        "material": "tài liệu",
        "fraction": "phần",
        "forest": "rừng",
        "sit": "ngồi",
        "race": "cuộc đua",
        "window": "cửa sổ",
        "store": "cửa hàng",
        "summer": "mùa hè",
        "train": "đào tạo",
        "sleep": "ngủ",
        "prove": "chứng minh",
        "lone": "đơn độc",
        "leg": "chân",
        "exercise": "tập thể dục",
        "wall": "tường",
        "catch": "bắt",
        "mount": "mount",
        "wish": "muốn",
        "sky": "bầu trời",
        "board": "hội đồng quản trị",
        "joy": "niềm vui",
        "winter": "mùa đông",
        "sat": "ngồi",
        "written": "bằng văn bản",
        "wild": "hoang dã",
        "instrument": "cụ",
        "kept": "giữ",
        "glass": "kính",
        "grass": "cỏ",
        "cow": "bò",
        "job": "công việc",
        "edge": "cạnh",
        "sign": "dấu hiệu",
        "visit": "lần",
        "past": "qua",
        "soft": "mềm",
        "fun": "vui vẻ",
        "bright": "sáng",
        "gas": "khí",
        "weather": "thời tiết",
        "month": "tháng",
        "million": "triệu",
        "bear": "chịu",
        "finish": "kết thúc",
        "happy": "hạnh phúc",
        "hope": "hy vọng",
        "flower": "hoa",
        "clothe": "mặc",
        "strange": "lạ",
        "gone": "ra đi",
        "trade": "thương mại",
        "melody": "giai điệu",
        "trip": "chuyến đi",
        "office": "văn phòng",
        "receive": "nhận",
        "row": "hàng",
        "mouth": "miệng",
        "exact": "chính xác",
        "symbol": "biểu tượng",
        "die": "chết",
        "least": "nhất",
        "trouble": "rắc rối",
        "shout": "hét lên",
        "except": "trừ",
        "wrote": "đã viết",
        "seed": "hạt giống",
        "tone": "giai điệu",
        "join": "tham gia",
        "suggest": "đề nghị",
        "clean": "sạch",
        "break": "nghỉ",
        "lady": "phụ nữ",
        "yard": "sân",
        "rise": "tăng",
        "bad": "xấu",
        "blow": "đòn",
        "oil": "dầu",
        "blood": "máu",
        "touch": "chạm",
        "grew": "tăng",
        "cent": "phần trăm",
        "mix": "trộn",
        "team": "đội",
        "wire": "dây",
        "cost": "chi phí",
        "lost": "thua",
        "brown": "nâu",
        "wear": "mặc",
        "garden": "vườn",
        "equal": "như nhau",
        "sent": "gửi",
        "choose": "chọn",
        "fell": "giảm",
        "fit": "phù hợp với",
        "flow": "chảy",
        "fair": "công bằng",
        "bank": "ngân hàng",
        "collect": "thu thập",
        "save": "lưu",
        "control": "kiểm soát",
        "decimal": "số thập phân",
        "ear": "tai",
        "else": "khác",
        "quite": "khá",
        "broke": "đã phá vỡ",
        "case": "khi",
        "middle": "trung",
        "kill": "giết",
        "son": "con trai",
        "lake": "hồ",
        "moment": "thời điểm",
        "scale": "quy mô",
        "loud": "lớn",
        "spring": "mùa xuân",
        "observe": "quan sát",
        "child": "con",
        "straight": "thẳng",
        "consonant": "phụ âm",
        "nation": "quốc gia",
        "dictionary": "từ điển",
        "milk": "sưa",
        "speed": "tốc độ",
        "method": "phương pháp",
        "organ": "cơ quan",
        "pay": "trả",
        "age": "tuổi",
        "section": "phần",
        "dress": "váy",
        "cloud": "điện toán đám mây",
        "surprise": "bất ngờ",
        "quiet": "yên tĩnh",
        "stone": "đá",
        "tiny": "nhỏ",
        "climb": "lên cao",
        "cool": "mát mẻ",
        "design": "thiết kế",
        "poor": "người nghèo",
        "lot": "rất nhiều",
        "experiment": "thí nghiệm",
        "bottom": "dưới",
        "key": "chính",
        "iron": "sắt",
        "single": "đơn",
        "stick": "thanh",
        "flat": "phẳng",
        "twenty": "hai mươi",
        "skin": "da",
        "smile": "nụ cười",
        "crease": "nếp",
        "hole": "lỗ",
        "jump": "nhảy",
        "baby": "bé",
        "eight": "tám",
        "village": "làng",
        "meet": "đáp ứng",
        "root": "gốc",
        "buy": "mua",
        "raise": "nâng cao",
        "solve": "giải quyết",
        "metal": "kim loại",
        "whether": "liệu",
        "push": "đẩy",
        "seven": "bảy",
        "paragraph": "đoạn",
        "third": "thứ ba",
        "shall": "có trách nhiệm",
        "held": "được tổ chức",
        "hair": "lông",
        "describe": "mô tả",
        "cook": "nấu ăn",
        "floor": "sàn",
        "either": "hoặc",
        "result": "kết quả",
        "burn": "ghi",
        "hill": "đồi",
        "safe": "an toàn",
        "cat": "mèo",
        "century": "thế kỷ",
        "consider": "xem xét",
        "type": "loại",
        "law": "pháp luật",
        "bit": "bit",
        "coast": "bờ biển",
        "copy": "bản sao",
        "phrase": "cụm từ",
        "silent": "im lặng",
        "tall": "cao",
        "sand": "cát",
        "soil": "đất",
        "roll": "cuộn",
        "temperature": "nhiệt độ",
        "finger": "ngón tay",
        "industry": "ngành công nghiệp",
        "value": "giá trị",
        "fight": "cuộc chiến",
        "lie": "lời nói dối",
        "beat": "đánh bại",
        "excite": "kích thích",
        "natural": "tự nhiên",
        "view": "xem",
        "sense": "ý nghĩa",
        "capital": "vốn",
        "won’t": "sẽ không",
        "chair": "ghế",
        "danger": "nguy hiểm",
        "fruit": "trái cây",
        "rich": "giàu",
        "thick": "dày",
        "soldier": "người lính",
        "process": "quá trình",
        "operate": "hoạt động",
        "practice": "thực hành",
        "separate": "riêng biệt",
        "difficult": "khó khăn",
        "doctor": "bác sĩ",
        "please": "xin vui lòng",
        "protect": "bảo vệ",
        "noon": "trưa",
        "crop": "cây trồng",
        "modern": "hiện đại",
        "element": "yếu tố",
        "hit": "nhấn",
        "student": "sinh viên",
        "corner": "góc",
        "party": "bên",
        "supply": "cung cấp",
        "whose": "có",
        "locate": "xác định vị trí",
        "ring": "vòng",
        "character": "nhân vật",
        "insect": "côn trùng",
        "caught": "bắt",
        "period": "thời gian",
        "indicate": "chỉ ra",
        "radio": "radio",
        "spoke": "nói",
        "atom": "nguyên tử",
        "human": "con người",
        "history": "lịch sử",
        "effect": "hiệu lực",
        "electric": "điện",
        "expect": "mong đợi",
        "bone": "xương",
        "rail": "đường sắt",
        "imagine": "tưởng tượng",
        "provide": "cho",
        "agree": "đồng ý",
        "thus": "do đó",
        "gentle": "nhẹ nhàng",
        "woman": "người phụ nữ",
        "captain": "đội trưởng",
        "guess": "đoán",
        "necessary": "cần thiết",
        "sharp": "sắc nét",
        "wing": "cánh",
        "create": "tạo",
        "neighbor": "hàng xóm",
        "wash": "rửa",
        "bat": "bat",
        "rather": "thay",
        "crowd": "đám đông",
        "corn": "ngô",
        "compare": "so sánh",
        "poem": "bài thơ",
        "string": "chuỗi",
        "bell": "chuông",
        "depend": "phụ thuộc",
        "meat": "thịt",
        "rub": "chà",
        "tube": "ống",
        "famous": "nổi tiếng",
        "dollar": "đồng đô la",
        "stream": "sông",
        "fear": "sợ hãi",
        "sight": "cảnh",
        "thin": "mỏng",
        "triangle": "tam giác",
        "planet": "hành tinh",
        "hurry": "nhanh",
        "chief": "trưởng",
        "colony": "thuộc địa",
        "clock": "đồng hồ",
        "mine": "tôi",
        "tie": "cà vạt",
        "enter": "nhập",
        "major": "chính",
        "fresh": "tươi",
        "search": "tìm kiếm",
        "send": "gửi",
        "yellow": "vàng",
        "gun": "súng",
        "allow": "cho phép",
        "print": "in",
        "dead": "chết",
        "spot": "tại chỗ",
        "desert": "sa mạc",
        "suit": "phù hợp với",
        "current": "hiện tại",
        "lift": "thang máy",
        "rose": "tăng",
        "arrive": "đến",
        "master": "chủ",
        "track": "theo dõi",
        "parent": "mẹ",
        "shore": "bờ",
        "division": "phân chia",
        "sheet": "tờ",
        "substance": "chất",
        "favor": "ủng hộ",
        "connect": "kết nối",
        "post": "bài",
        "spend": "chi tiêu",
        "chord": "hợp âm",
        "fat": "chất béo",
        "glad": "vui",
        "original": "ban đầu",
        "share": "chia sẻ",
        "station": "trạm",
        "dad": "cha",
        "bread": "bánh mì",
        "charge": "phí",
        "proper": "thích hợp",
        "bar": "thanh",
        "offer": "phục vụ",
        "segment": "phân khúc",
        "slave": "nô lệ",
        "duck": "vịt",
        "instant": "ngay lập tức",
        "market": "thị trường",
        "degree": "mức độ",
        "populate": "cư",
        "chick": "gà",
        "dear": "thân yêu",
        "enemy": "kẻ thù",
        "reply": "trả lời",
        "drink": "ly",
        "occur": "xảy ra",
        "support": "hỗ trợ",
        "speech": "bài phát biểu",
        "nature": "thiên nhiên",
        "range": "phạm vi",
        "steam": "hơi nước",
        "motion": "chuyển động",
        "path": "con đường",
        "liquid": "chất lỏng",
        "log": "đăng nhập",
        "meant": "có nghĩa là",
        "quotient": "thương",
        "teeth": "răng",
        "shell": "vỏ",
        "neck": "cổ",
        "oxygen": "oxy",
        "sugar": "đường",
        "death": "chết",
        "pretty": "khá",
        "skill": "kỹ năng",
        "women": "phụ nữ",
        "season": "mùa",
        "solution": "giải pháp",
        "magnet": "nam châm",
        "silver": "bạc",
        "thank": "cảm ơn",
        "branch": "chi nhánh",
        "match": "trận đấu",
        "suffix": "hậu tố",
        "especially": "đặc biệt là",
        "fig": "sung",
        "afraid": "sợ",
        "huge": "to",
        "sister": "em gái",
        "steel": "thép",
        "discuss": "thảo luận",
        "forward": "về phía trước",
        "similar": "tương tự",
        "guide": "hướng dẫn",
        "experience": "kinh nghiệm",
        "score": "điểm",
        "apple": "táo",
        "bought": "mua",
        "led": "dẫn",
        "pitch": "sân",
        "coat": "áo",
        "mass": "khối lượng",
        "card": "thẻ",
        "band": "ban nhạc",
        "rope": "dây",
        "slip": "trượt",
        "win": "giành chiến thắng",
        "dream": "mơ",
        "evening": "buổi tối",
        "condition": "điều kiện",
        "feed": "thức ăn chăn nuôi",
        "tool": "công cụ",
        "total": "tổng số",
        "basic": "cơ bản",
        "smell": "mùi",
        "valley": "thung lũng",
        "nor": "cũng không",
        "double": "đôi",
        "seat": "ghế",
        "continue": "tiếp tục",
        "block": "khối",
        "chart": "biểu đồ",
        "hat": "mũ",
        "sell": "bán",
        "success": "thành công",
        "company": "công ty",
        "subtract": "trừ",
        "event": "sự kiện",
        "particular": "riêng",
        "deal": "thỏa thuận",
        "swim": "bơi",
        "term": "hạn",
        "opposite": "ngược lại",
        "wife": "vợ",
        "shoe": "giày",
        "shoulder": "vai",
        "spread": "lây lan",
        "arrange": "sắp xếp",
        "camp": "trại",
        "invent": "phát minh",
        "cotton": "bông",
        "born": "Sinh",
        "determine": "xác định",
        "quart": "lít",
        "nine": "chín",
        "truck": "xe tải",
        "noise": "tiếng ồn",
        "level": "mức",
        "chance": "cơ hội",
        "gather": "thu thập",
        "shop": "cửa hàng",
        "stretch": "căng ra",
        "throw": "ném",
        "shine": "tỏa sáng",
        "property": "tài sản",
        "column": "cột",
        "molecule": "phân tử",
        "select": "chọn",
        "wrong": "sai",
        "gray": "màu xám",
        "repeat": "lặp lại",
        "require": "yêu cầu",
        "broad": "rộng",
        "prepare": "chuẩn bị",
        "salt": "muối",
        "nose": "mui",
        "plural": "số nhiều",
        "anger": "tức giận",
        "claim": "xin",
        "continent": "lục"     
   }

   static getWords(){
      return MyChineseWords.words;
   }
}

export default MyVietnameseWords;
